let locHash = window.location.hash.split("");
locHash.shift();
let locHashNum = parseInt(locHash.join(""));

let content = selectElement(".content");

let glossaries = [
	[],
	[
		"comfortably - kényelmesen",
		"Good morning - Jó reggelt!",
		"Good afternoon - Jó napot!",
		"Good evening - Jó estét!",
		"Hi - Szia",
		"Hello - Szia",
		"to introduce oneself - bemutatkozni",
		"When? - Mikor?",
		"Am - Délelőtt",
		"Pm - Délután",
		"Five - Öt",
		"My name is …. …. -nak/-nek hívnak",
		"Wife - Feleség",
		"Husband - Férj",
		"Bye - Viszlát!",
		"Goodbye - Viszontlátásra!",
		"conversation - beszélgetés",
		"to leave - elmenni",
		"verb - ige",
		"easy - könnyű",
		"hard - nehéz",
		"numbers 1-10 - számok 0-10-ig",
		"ordinal numbers 1-10 - sorszámnevek 1-10",
		"equals - egyenlő",
		"days of the week - a hét napjai",
		"months of the year - az év hónapjai",
		"singular - egyes szám",
		"plura -l többes szám",
		"result - eredmény",
		"first - első",
		"last - utolsó"
	],
	[
		"remember - emlékezni",
		"octopus - polip",
		"student(s) - diák(ok)",
		"the alphabet - ABC",
		"letter - betű",
		"to spell - betűzni",
		"how? - hogy / hogyan?",
		"numbers - számok",
		"ordinal numbers - sorszámnevek",
		"a / an - egy (határozatlan névelő)",
		"normally - általában",
		"usually - rendszerint",
		"vowel - magánhangzó",
		"consonant - mássalhangzó",
		"owl - bagoly",
		"computer - számítógép",
		"pencil - ceruza",
		"pen - toll",
		"keyboard - billentyűzet",
		"mouse - egér",
		"girl - lány",
		"boy - fiú",
		"aadvark - földimalac",
		"axe - fejsze",
		"ear - fül",
		"knee - térd",
		"leg - láb",
		"arm - kar",
		"eye - szem",
		"nose - orr",
		"head - fej",
		"ostrich - strucc",
		"pig - disznó",
		"cow - tehén",
		"stomach - gyomor",
		"mouth - száj",
		"neck - nyak",
		"shoulder - váll",
		"chest - mellkas",
		"thigh - comb",
		"calf - vádli",
		"shin - sípcsont",
		"ankle - boka",
		"upper arm - felkar",
		"elbow - könyök",
		"forearm - alkar",
		"wrist - csukló",
		"hand - kéz",
		"palm - tenyér",
		"finger - ujj",
		"thumb - hüvelykujj",
		"cheek - orca",
		"chin - áll",
		"jaw - állkapocs",
		"French - francia",
		"happy - boldog",
		"intelligent - okos",
		"tanned - napbarnított",
		"married - házas",
		"single - egyedülálló",
		"cheap - olcsó",
		"cold - hideg",
		"Spanish - spanyol",
		"tall - magas",
		"ugly - csúnya",
		"attractive - vonzó",
		"thirsty - szomjas",
		"hungry - éhes",
		"flower - virág",
		"car - autó",
		"house - ház",
		"apple - alma",
		"box - doboz",
		"bus - busz",
		"church - templom",
		"toothbrush - fogkefe",
		"monkey - majom",
		"lady - hölgy",
		"baby - csecsemő",
		"fly - légy",
		"knife - kés",
		"shelf - polc",
		"umbrella - esernyő",
		"family - család",
		"boat - hajó",
		"bicycle - bicikli",
		"desk - íróasztal",
		"watch - karóra",
		"shoe - cipő",
		"shirt - ing",
		"T-shirt - póló",
		"sock - zokni",
		"leaf - levél",
		"thief - tolvaj",
		"wolf - farkas",
		"fat - kövér",
		"beautiful - gyönyörű",
		"to practise - gyakorolni"
	],
	[
		"noun - főnév",
		"differenc - különböző",
		"brush - kefe",
		"remember - emlékezni",
		"pastry - sütemény",
		"man - férfi",
		"child - gyerek",
		"sheep - birka",
		"trousers - nadrág",
		"shorts - sort",
		"sheep - bárány",
		"glasses - szemüveg",
		"jeans - farmernadrág",
		"scissors - olló",
		"ring - gyűrű",
		"helmet - sisak",
		"skateboard - gördeszka",
		"elbow pad - könyökvédő",
		"knee pad - térdvédő",
		"key - kulcs",
		"son - fiú gyermek",
		"daughter - lány gyerek",
		"squirrel - mókus",
		"shoelace - cipőfűző",
		"footballer - focista",
		"policeman - rendőr",
		"country - ország",
		"nationality - nemzetiség",
		"famous - híres",
		"object - tárgy",
		"guitar - gitár",
		"passport - útlevél",
		"date of birth - születési dátum",
		"place of birth - születési hely",
		"Where are you from? - Honnan való vagy?",
		"first name - keresztnév",
		"surname - családi név / vezetéknév",
		"When? - Mikor?",
		"What? - Mit?",
		"Where? - Hol? / Hova?"
	],
	[
		"owner - tulajdonos",
		"bowl - tál",
		"tail - farok",
		"stethoscope - sztetoszkóp",
		"example - példa",
		"place - hely",
		"noon - dél",
		"to improve - megjavít",
		"probably - várható",
		"likely - valószínű",
		"pattern - séma",
		"to spell - betűz",
		"different - más",
		"black - fekete",
		"white - fehér",
		"red - piros / vörös",
		"orange - narancssárga",
		"yellow - sárga",
		"green - zöld",
		"blue - kék",
		"pink - rózsaszín",
		"grey - szürke",
		"brown - barna",
		"ribbon - szalag",
		"autumn - ősz",
		"near - közel",
		"far - messze",
		"hyphen - kötőjel"
	],
	[
		"comfortably - kényelmesen",
		"Good morning - Jó reggelt!",
		"Good afternoon - Jó napot!",
		"Good evening - Jó estét!",
		"Hi - Szia",
		"Hello - Szia",
		"to introduce oneself - bemutatkozni",
		"When? - Mikor?",
		"Am - Délelőtt",
		"Pm - Délután",
		"Five - Öt",
		"My name is …. …. -nak/-nek hívnak",
		"Wife - Feleség",
		"Husband - Férj",
		"Bye - Viszlát!",
		"Goodbye - Viszontlátásra!",
		"conversation - beszélgetés",
		"to leave - elmenni",
		"verb - ige",
		"easy - könnyű",
		"hard - nehéz",
		"numbers 1-10 - számok 0-10-ig",
		"ordinal numbers 1-10 - sorszámnevek 1-10",
		"equals - egyenlő",
		"days of the week - a hét napjai",
		"months of the year - az év hónapjai",
		"singular - egyes szám",
		"plura -l többes szám",
		"result - eredmény",
		"first - első",
		"last - utolsó",
		"remember - emlékezni",
		"octopus - polip",
		"student(s) - diák(ok)",
		"the alphabet - ABC",
		"letter - betű",
		"to spell - betűzni",
		"how? - hogy / hogyan?",
		"numbers - számok",
		"ordinal numbers - sorszámnevek",
		"a / an - egy (határozatlan névelő)",
		"normally - általában",
		"usually - rendszerint",
		"vowel - magánhangzó",
		"consonant - mássalhangzó",
		"owl - bagoly",
		"computer - számítógép",
		"pencil - ceruza",
		"pen - toll",
		"keyboard - billentyűzet",
		"mouse - egér",
		"girl - lány",
		"boy - fiú",
		"aadvark - földimalac",
		"axe - fejsze",
		"ear - fül",
		"knee - térd",
		"leg - láb",
		"arm - kar",
		"eye - szem",
		"nose - orr",
		"head - fej",
		"ostrich - strucc",
		"pig - disznó",
		"cow - tehén",
		"stomach - gyomor",
		"mouth - száj",
		"neck - nyak",
		"shoulder - váll",
		"chest - mellkas",
		"thigh - comb",
		"calf - vádli",
		"shin - sípcsont",
		"ankle - boka",
		"upper arm - felkar",
		"elbow - könyök",
		"forearm - alkar",
		"wrist - csukló",
		"hand - kéz",
		"palm - tenyér",
		"finger - ujj",
		"thumb - hüvelykujj",
		"cheek - orca",
		"chin - áll",
		"jaw - állkapocs",
		"French - francia",
		"happy - boldog",
		"intelligent - okos",
		"tanned - napbarnított",
		"married - házas",
		"single - egyedülálló",
		"cheap - olcsó",
		"cold - hideg",
		"Spanish - spanyol",
		"tall - magas",
		"ugly - csúnya",
		"attractive - vonzó",
		"thirsty - szomjas",
		"hungry - éhes",
		"flower - virág",
		"car - autó",
		"house - ház",
		"apple - alma",
		"box - doboz",
		"bus - busz",
		"church - templom",
		"toothbrush - fogkefe",
		"monkey - majom",
		"lady - hölgy",
		"baby - csecsemő",
		"fly - légy",
		"knife - kés",
		"shelf - polc",
		"umbrella - esernyő",
		"family - család",
		"boat - hajó",
		"bicycle - bicikli",
		"desk - íróasztal",
		"watch - karóra",
		"shoe - cipő",
		"shirt - ing",
		"T-shirt - póló",
		"sock - zokni",
		"leaf - levél",
		"thief - tolvaj",
		"wolf - farkas",
		"fat - kövér",
		"beautiful - gyönyörű",
		"to practise - gyakorolni",
		"noun - főnév",
		"differenc - különböző",
		"brush - kefe",
		"remember - emlékezni",
		"pastry - sütemény",
		"man - férfi",
		"child - gyerek",
		"sheep - birka",
		"trousers - nadrág",
		"shorts - sort",
		"sheep - bárány",
		"glasses - szemüveg",
		"jeans - farmernadrág",
		"scissors - olló",
		"ring - gyűrű",
		"helmet - sisak",
		"skateboard - gördeszka",
		"elbow pad - könyökvédő",
		"knee pad - térdvédő",
		"key - kulcs",
		"son - fiú gyermek",
		"daughter - lány gyerek",
		"squirrel - mókus",
		"shoelace - cipőfűző",
		"footballer - focista",
		"policeman - rendőr",
		"country - ország",
		"nationality - nemzetiség",
		"famous - híres",
		"object - tárgy",
		"guitar - gitár",
		"passport - útlevél",
		"date of birth - születési dátum",
		"place of birth - születési hely",
		"Where are you from? - Honnan való vagy?",
		"first name - keresztnév",
		"surname - családi név / vezetéknév",
		"When? - Mikor?",
		"What? - Mit?",
		"Where? - Hol? / Hova?",
		"owner - tulajdonos",
		"bowl - tál",
		"tail - farok",
		"stethoscope - sztetoszkóp",
		"example - példa",
		"place - hely",
		"noon - dél",
		"to improve - megjavít",
		"probably - várható",
		"likely - valószínű",
		"pattern - séma",
		"to spell - betűz",
		"different - más",
		"black - fekete",
		"white - fehér",
		"red - piros / vörös",
		"orange - narancssárga",
		"yellow - sárga",
		"green - zöld",
		"blue - kék",
		"pink - rózsaszín",
		"grey - szürke",
		"brown - barna",
		"ribbon - szalag",
		"autumn - ősz",
		"near - közel",
		"far - messze",
		"hyphen - kötőjel"
	],
	[
		"verb - ige",
		"verbs - igék",
		"to come - jön",
		"to live - él",
		"to go - megy",
		"to work - dolgozik",
		"to read - olvas",
		"to write - ír",
		"to drive - vezet",
		"to walk - sétál",
		"to run - fut",
		"to swim - úszik",
		"to like - kedvel / tetszik",
		"to love - szeret",
		"to wash - mos",
		"to wake up - felébred",
		"to get up - felkel",
		"to fly - repül",
		"to carry - visz",
		"always - mindig",
		"never - soha",
		"every day - minden nap",
		"every Saturday - minden szombaton",
		"sometimes - néha",
		"three times a week - hetente háromszor",
		"every weekend - minden hétvégén",
		"twice a year - évente kétszer",
		"usually - általában",
		"normally - általában",
		"When / when? - Amikor / Mikor?",
		"How often? - Milyen gyakran?",
		"nearly always - majdnem mindig",
		"daily routine - napi rutin",
		"everything else - minden más",
		"to have a shower - zuhanyzik",
		"to shave - borotválkozik",
		"to dry - szárítani",
		"to brush your teeth - fogat mos",
		"to comb - fésülködik",
		"to get dressed - felöltözik",
		"to cook - főz",
		"to drink - iszik",
		"to wash up - elmosogat",
		"to put on - felvesz",
		"parent - szülő",
		"parents - szülők",
		"grandparent - nagyszülő",
		"grandparents - nagyszülők",
		"not likely - nem valószínű",
		"to kiss - csókol",
		"to fix / to repair - megjavít",
		"to fish - halászik",
		"occupation - foglalkozás",
		"job - állás",
		"nurse - nővér",
		"butcher - hentes",
		"waiter - pincér",
		"cashier - pénztáros",
		"shop assistant - eladó",
		"plumber - vízvezeték szerelő",
		"bus driver - buszvezető",
		"librarian - könyvtáros",
		"dentist - fogorvos",
		"cleaner - takarító",
		"pilot - pilóta",
		"soldier - katona",
		"hairdresser - fodrász",
		"barber - borbély",
		"architect - építész",
		"to protect - megvéd",
		"to attack - támad",
		"to defend - véd",
		"to bring - hoz",
		"to cut - vág",
		"to find - talál",
		"to start - kezd",
		"to finish - befejez",
		"to plan - tervez",
		"to draw - rajzol",
		"to sell - elad",
		"to use - használ",
		"to connect - összeköt / kapcsol",
		"to telephone / to phone - telefonál",
		"to clean - takarít / tisztít",
		"to borrow - kölcsönkér",
		"a bill - számla",
		"a gun - lőfegyver",
		"a uniform - egyenruha",
		"a plan - terv",
		"to punch - ütni"
	],
	[
		"to revise - átnéz",
		"a bowl of … - egy tál …",
		"a bottle - egy palack",
		"a can - egy doboz",
		"a piece of … - egy darab …",
		"a carton of … - egy kartondoboz …",
		"a slice of … - egy szelet …",
		"a glass of … - egy pohár …",
		"a list - lista",
		"cardinal number - tőszám",
		"to feel - érez",
		"puppy - kiskutya",
		"sheep - birka",
		"to pray - imádkozik",
		"to double - megdupláz",
		"to combine - egyesít",
		"correct - helyes"
	],
	[
		"nice - szép",
		"on - -on, -en, -ön",
		"unde - alatt",
		"next t - mellett",
		"a page - lap",
		"a contract - szerződés",
		"to write - aláír",
		"ill - beteg",
		"hospital - kórház",
		"favourite - kedvenc",
		"cit - város",
		"news - hír",
		"hero - hős",
		"strange - furcsa",
		"hole - lyuk",
		"motorway - autópálya",
		"to study - tanul",
		"docto - orvos",
		"dentist - fogorvos",
		"hairdresser - fodrász",
		"beautician - kozmetikus",
		"train - vonat",
		"party - buli",
		"airport - repülőtér",
		"train station - vasúti pályaudvar",
		"bus station - buszpályaudvar",
		"police station - rendőrörs",
		"floor - padló / emelet",
		"ground floor - földszint",
		"1st floor - első emelet",
		"2nd floor - második emelet",
		"on the 78th floor - a 78. emeleten",
		"tram - villamos",
		"adjective-opposite - melléknév ellentéte",
		"good - jó",
		"bad - rossz",
		"unhappy / sad - szomorú",
		"open - nyitott",
		"closed - zárt",
		"wet - nedves",
		"dry - száraz",
		"fast - gyors",
		"slow - lassú",
		"hard - kemény",
		"soft - puha",
		"high - magas",
		"low - alacsony",
		"big - nagy",
		"small - kicsi",
		"young - fiatal",
		"old - öreg / régi",
		"rich - gazdag",
		"poor - szegény",
		"new - új",
		"tall - magas",
		"short - alacsony",
		"expensive - drága",
		"cheap - olcsó",
		"strong - erős",
		"weak - gyenge",
		"full - tele",
		"empty - üres",
		"thick - vastag",
		"thin - vékony",
		"hot - forró",
		"cold - hideg",
		"to describe - leír",
		"appearance - külső megjelenés",
		"what somebody looks like - hogy néz ki valaki",
		"very - nagyon",
		"to wear - visel",
		"clothes - ruha",
		"a suit - öltöny",
		"trousers - nadrág",
		"jeans - farmernadrág",
		"tights - harisnyanadrág",
		"dress - ruha",
		"jumper - pulóver",
		"middle-aged - középkorú",
		"bald - kopasz",
		"to modify - módosít",
		"power - erő"
	],
	[
		"first name - keresztnév",
		"surname - családi név",
		"maiden name - lánykori név",
		"to marry - házasodik",
		"single - egyedülálló",
		"walking stick - sétabot",
		"father-in-law - após",
		"mother-in-law - anyós",
		"sister-in-law - sógornő",
		"brother-in-law - sógor",
		"son-in-law - vej",
		"daughter-in-law - meny",
		"grandchild - unoka",
		"grandson - fiúunoka",
		"granddaughter - lányunoka",
		"relationship - kapcsolat",
		"closer - közelebb",
		"beside - mellett",
		"between - között",
		"in front of - előtt",
		"behind - mögött",
		"above - valami felett",
		"below - valami alatt",
		"approximately - körülbelől",
		"-ish - körülbelül",
		"trainers - tornacipő",
		"fridge - hűtőszekrény",
		"freezer - fagyasztó",
		"some - néhány",
		"frozen - fagyasztott",
		"refrigerated - hűtött",
		"sentence - mondat"
	],
	[
		"to walk - sétál",
		"to play - játszik",
		"to carry - visz",
		"meat - hús",
		"to help - segít",
		"to look after - gondoskodik",
		"to defend - véd",
		"to cut - vág",
		"to bring - hoz",
		"thing - dolog",
		"a drink - egy ital",
		"food - étel",
		"to pronounce - kiejt",
		"pronunciation - kiejtés"
	],
	[
		"ability - képesség",
		"possible - lehetséges",
		"not possible - nem lehetséges",
		"impossible - lehetetlen",
		"polite - udvarias",
		"impolite - udvariatlan",
		"rude (very impolite) - goromba",
		"of course - természetesen",
		"to receive - kap",
		"to get - kap",
		"a question - kérdés",
		"an answer - válasz",
		"to ask a question - kérdez",
		"to reply - válaszol",
		"just a moment - egy pillanat",
		"to compare - összehasonlít",
		"a comparison - összehasonlítás",
		"same - ugyanaz",
		"similar - hasonló",
		"different - különböző",
		"to spot - észrevesz",
		"like - tetszik",
		"love - szeret",
		"want - akar",
		"need - szüksége van",
		"know - tud",
		"understand - ért",
		"remember - emlékszik",
		"forget - elfelejt",
		"prefer - jobban tetszik",
		"hate - gyűlöl",
		"mean - gondol",
		"believe - hisz",
		"hammer - kalapács",
		"sideburns - pajesz",
		"to fight - harcol",
		"crime fighter - bűnözés elleni harcos",
		"superhero - szuperhős",
		"to excercise - edz",
		"to work out (synonym for excercise) - edz",
		"permanent - állandó",
		"temporary - átmeneti",
		"job - állás",
		"cocktail - koktél",
		"unicorn - egyszarvú",
		"parrot - papagáj",
		"horse - ló",
		"cheetah - gepárd",
		"kangaroo - kenguru",
		"elephant - elefánt",
		"frog - béka",
		"fly - légy",
		"wing - szárny",
		"to kill - öl",
		"to destroy - elpusztít",
		"a planet - bolygó",
		"a magazine - magazin",
		"a magazine cover - címlap",
		"it's raining - esik az eső",
		"street - utca",
		"to fall - esni",
		"sky - ég",
		"puddle - tócsa",
		"windscreen wipers - ablaktörlő",
		"mask - álarc",
		"shoulder pad - válltömés",
		"top - felső",
		"biceps - bicepsz",
		"haircut - frizura"
	],
	[
		"want - akar",
		"prefer - jobban tetszik",
		"forget - elfelejt",
		"sibling - testvér",
		"boot - csizma / bakancs",
		"ankle - boka",
		"uncle - nagybácsi",
		"aunt - nagynéni",
		"nephew - unokaöcs",
		"niece - unokahúg",
		"similarity - hasonlóság",
		"difference - különbség",
		"petrol - benzin",
		"petrol station - benzinkút",
		"remote control - távirányító",
		"to make a decision - dönteni",
		"older - örgebb / idősebb",
		"shorter - alacsonyabb / rövidebb",
		"happier - boldogabb",
		"easier - könnyebb",
		"careful - óvatos",
		"more careful - óvatosabb",
		"more expensive - drágább",
		"interesting - érdekes",
		"more interesting - érdekesebb",
		"well - jól",
		"good - jó",
		"better - jobb",
		"bad - rossz",
		"worse - rosszabb",
		"modern - modern",
		"more modern - modernebb",
		"larger - nagyobb",
		"intelligent - intelligens",
		"more intelligent - intelligensebb"
	],
	[
		"piffle - szamárság",
		"luck - szerencse",
		"lucky - szerencsés",
		"unlucky - szerencsétlen",
		"certain - biztos",
		"question mark - kérdőjel",
		"he's asleep - alszik",
		"accident - baleset",
		"motorway - autópálya",
		"today - ma",
		"yesterday - tegnap",
		"the day before yesterday - tegnapelőtt",
		"tomorrow - holnap",
		"the day after tomorrow - holnapután",
		"swift - gyors",
		"swiftly - gyorsan",
		"confident - magabiztos",
		"to jump - ugrik",
		"place - hely",
		"movement - mozgás",
		"ATM - bankautomata",
		"lock - zár",
		"to open - kinyit",
		"to put into gear - sebességbe kapcsol",
		"would you like? - szeretne?",
		"want - akar",
		"what would you like? - mit szeretne?",
		"what do you want? - mit akarsz?",
		"awful - szörnyű",
		"terrible - borzasztó",
		"horrible - rémes",
		"deaf - süket",
		"staff - személyzet",
		"to offer - kínál / ajánl",
		"nice - kedves",
		"popular - népszerű",
		"unpopular - népszerűtlen",
		"general - általános",
		"specific - konkrét",
		"to record - felvesz",
		"to bake - süt",
		"to watch - figyel",
		"to copy - másol",
		"to marry - házasodik",
		"to study - tanul",
		"a winery - borászat",
		"a cellar - pince",
		"dinner - vacsora",
		"a restaurant - étterem",
		"pork - disznóhús",
		"chicken - csirke",
		"spinach - spenót",
		"pumpkin - tök",
		"mashed potato - krumplipüré",
		"to begin - kezd",
		"to buy - kezd",
		"to eat - eszik",
		"to find - talál",
		"to give - ad",
		"to think - gondol"
	],
	[
		"potato - burgonya, krumpli",
		"onion - hagyma",
		"goose - liba",
		"turkey - pulyka",
		"Christmas present - karácsonyi ajándék",
		"Christmas carol - karácsonyi ének",
		"a tie - nyakkendő",
		"skull - koponya",
		"gloves - kesztyű",
		"wooly hat - kötött sapka",
		"to wrap - csomagol",
		"to decorate - díszít",
		"vegetables - zöldség",
		"carrot - sárgarépa",
		"Brussels sprout - kelbimbó",
		"cabbage - káposzta",
		"meat - hús",
		"goose leg - libacomb",
		"garlic - fokhagyma",
		"to buy - bought - vesz",
		"to brind - brought - hoz",
		"recipe - recept",
		"ingredients - hozzávalók / összetevők",
		"flour - liszt",
		"bicarbonate of soda - szódabikarbóna",
		"teaspoon - teáskanál",
		"table spoon - evőkanál",
		"ginger - gyömbér",
		"to grind - ground - őröl",
		"ground - őrölt",
		"cinnamon - fahéj",
		"I don't know - nem tudom",
		"I don't care - nem érdekel",
		"to forget - forgot - elfelejt",
		"not important - nem fontos",
		"egg - tojás",
		"to lay en egg - tojást tojni",
		"fried egg - tükörtojás",
		"molasses - melasz",
		"viscous - nyúlós",
		"sieve - szita",
		"to sift - sifted - szitál",
		"food mixer - konyhai robotgép",
		"to mix - kever",
		"to rub - dörzsöl",
		"to collect - összegyűjt",
		"to throw - dob",
		"breadcrumbs - zsemlemorzsa",
		"fork - villa",
		"whisk - habverő",
		"rolling pin - sodrófa",
		"to confuse - összezavar",
		"confused - zavart",
		"to celebrate - ünnepel",
		"a source - forrás",
		"religious festival - vallási ünnep",
		"the day before - előző nap",
		"to play - játszik",
		"to prepare - készít",
		"to organise - szervez",
		"to turn of - bekapcsol",
		"to turn off - kikapcsol",
		"a hob - főzőlap",
		"an oven - sütő",
		"important - fontos",
		"stress - stressz",
		"naturally - természetesen",
		"traditionally - hagyományosan",
		"tradition - hagyomány",
		"it depends - attól függ",
		"tree trunk - fatörzs",
		"fairy lights - karácsonyi égők",
		"nasty - komisz",
		"a miser - fösvény",
		"to spend - költ",
		"pots of money - nagyon sok pénz",
		"huge amount of cash - rengeteg készpénz",
		"candle - gyertya",
		"a money-lender - hitelező",
		"a usurer - uzsora",
		"to charge interest - kamatot felszámít",
		"fair - tisztességes",
		"to exploit - kihasznál",
		"on time - időben",
		"to be late - késik",
		"te deduct - levon",
		"salt - só",
		"lunchtime - ebédidő",
		"toilet paper - WC papír",
		"day off - szabadnap",
		"to count - számol",
		"a ghost - szellem",
		"almost - majdnem",
		"to wet the bed - az ágyba vizelni",
		"business - cég",
		"to be nice - kedves lenni",
		"for ever and ever - örökké",
		"to show - mutat",
		"portable - hordozható",
		"to remind - emlékeztet",
		"a girlfriend - barátnő",
		"a boss - főnök",
		"to leave - elmegy",
		"a boss - főnök",
		"to arrive - érkezik",
		"dead - halott",
		"to die - meghal",
		"nobody - senki",
		"to visit - látogat",
		"a grave - sír",
		"upset - felizgatott",
		"to feel - érez",
		"a couple - pár",
		"go to sleep - went to sleep - elalszik",
		"to wake up - woke up - felébred",
		"mean - fukar",
		"stingy - fukar",
		"to rush - rushed - rohan",
		"suprised - meglepődött",
		"a present - ajándék",
		"lyrics - dalszöveg",
		"title - cím",
		"weird - furcsa",
		"partridge - fogoly",
		"pear tree - körtefa",
		"turtle-dove - gerle",
		"blackbird - rigó",
		"gold - arany",
		"who cares? - kit érdekel?",
		"rhythm - ritmus",
		"swan - hattyú",
		"maid - leány",
		"to leap - ugrik",
		"rabbit - nyúl",
		"grasshopper - szöcske",
		"piper - dudás",
		"bagpipes - duda",
		"a drummer - dobos",
		"to drum - dobol",
		"chat - csevegés",
		"reason - ok",
		"to fill - tölt",
		"air - levegő",
		"crescendo - fokozatos erősödés",
		"to imagine - imagined - elképzel",
		"stage - színpad",
		"microphone - mikrofon",
		"loudspeaker - hangszóró",
		"lung(s) - tüdő(k)",
		"audience - közönség",
		"ceiling - plafon",
		"curly - göndör",
		"straight - egyenes",
		"quiet - csendes",
		"loud - hangos",
		"louder - hangosabb",
		"to sing - énekel",
		"to release - kienged",
		"to damage - megkárosít"
	],
	[
		"too much - túl sokat",
		"to put on weight - hízik",
		"success - siker",
		"permission - engedély",
		"hopefully - remélhetőleg",
		"to recover - felépül",
		"relaxed - kipihent",
		"refreshed - felfrissül"
	],
	[
		"to continue - folytatódik",
		"how far from…? - milyen messze … -tól/-től?",
		"a headache - fejfájás",
		"a stomach ache - gyomorfájás",
		"to hurt - fáj",
		"to ache - fáj",
		"painful - fájdalmas",
		"a hangover - másnaposság",
		"to be hung-over - másnapos",
		"to have a cold - meg van fázva",
		"an infection - fertőzés",
		"blocked - eldugult",
		"sneeze - tüsszent",
		"damp - nedves",
		"soaking wet - bőrig ázott",
		"to be in the doghouse - büntetésben van",
		"eccentric - különc",
		"elegant - elegáns",
		"eclectic - eklektikus",
		"electric eel - elektromos angolna",
		"to pay attention - figyelni",
		"type - típus",
		"yellow-ish - sárgás",
		"carbonated - szénsavas",
		"bubbles - buborék",
		"phrase - kifejezés",
		"useful - hasznos",
		"to order - rendes",
		"a pint of beer - 1 korsó sör",
		"a 1/2 pint of beer - 1 pohár sör",
		"shandy - radler",
		"lemonade - szénvasas limonádé",
		"table service - kiszolgálás az asztalnál",
		"counter service - kiszolgálás a pultnál",
		"to tip - borravalót adni",
		"a tip - borravaló",
		"a bench - pad",
		"to fall asleep - elalszik",
		"wetter than … - vizesebb mint …",
		"to cough - köhög",
		"to sneeze - tüsszent",
		"to have a sore throat - fáj a torka",
		"to have a blocked nose - eldugult az orra",
		"rabies - veszettség",
		"originally - eredetileg",
		"disease - betegség",
		"to convince - meggyőz",
		"to realize - észrevesz",
		"I'm sorry - sajnálom",
		"to behave - viselkedik",
		"badly - rosszul",
		"to forgive - megbocsát",
		"to accept - elfogad",
		"the matter is closed - az ügy le van zárva",
		"excuse me - elnézést kérek",
		"sorry - bocsánat",
		"to move - mozog",
		"to get someone's attention - valakinek a figyelmét felhívni",
		"to wave - int",
		"a crowd - tömeg",
		"to force - erőltet",
		"to pass - elhalad",
		"to interrupt - félbeszakít",
		"to miss - lemarad",
		"celebration - ünneplés",
		"adjective - melléknév",
		"adverb - határozószó",
		"how - hogy / hogyan",
		"quick - gyors",
		"quickly - gyorsan",
		"slowly - lassan",
		"opposite - ellentét",
		"to add - hozzáad",
		"to provide - nyújt",
		"together - együtt",
		"a couple - pár",
		"automatically - automatikusan",
		"extra - plusz",
		"nice - szép",
		"neat - rendezett",
		"a mistake - hiba",
		"heavily - nehezen",
		"awkward - kellemetlen",
		"to accelerate - gyorsul",
		"quietly - csendesen",
		"loudly - hangosan",
		"a runny nose - folyik az orr",
		"liquid - folyadék",
		"a tissue - papírzsebkendő",
		"to have a temperature - valakinek láza van",
		"fever - láz",
		"to bump into - összefut valakivel"
	],
	[
		"verb - ige",
		"verbs - igék",
		"to come - jön",
		"to live - él",
		"to go - megy",
		"to revise - átnéz",
		"a bowl of … - egy tál …",
		"a bottle - egy palack",
		"a can - egy doboz",
		"a piece of … - egy darab …",
		"nice - szép",
		"on - -on, -en, -ön",
		"unde - alatt",
		"next t - mellett",
		"a page - lap",
		"a contract - szerződés",
		"to write - aláír",
		"ill - beteg",
		"hospital - kórház",
		"favourite - kedvenc",
		"cit - város",
		"news - hír",
		"hero - hős",
		"first name - keresztnév",
		"surname - családi név",
		"maiden name - lánykori név",
		"to marry - házasodik",
		"single - egyedülálló",
		"walking stick - sétabot",
		"father-in-law - após",
		"mother-in-law - anyós",
		"sister-in-law - sógornő",
		"brother-in-law - sógor",
		"son-in-law - vej",
		"daughter-in-law - meny",
		"grandchild - unoka",
		"grandson - fiúunoka",
		"granddaughter - lányunoka",
		"relationship - kapcsolat",
		"to walk - sétál",
		"to play - játszik",
		"to carry - visz",
		"meat - hús",
		"to help - segít",
		"to look after - gondoskodik",
		"to defend - véd",
		"ability - képesség",
		"possible - lehetséges",
		"not possible - nem lehetséges",
		"impossible - lehetetlen",
		"polite - udvarias",
		"impolite - udvariatlan",
		"rude (very impolite) - goromba",
		"of course - természetesen",
		"to receive - kap",
		"to get - kap",
		"want - akar",
		"prefer - jobban tetszik",
		"forget - elfelejt",
		"sibling - testvér",
		"boot - csizma / bakancs",
		"ankle - boka",
		"uncle - nagybácsi",
		"aunt - nagynéni",
		"nephew - unokaöcs",
		"niece - unokahúg",
		"piffle - szamárság",
		"luck - szerencse",
		"lucky - szerencsés",
		"unlucky - szerencsétlen",
		"certain - biztos",
		"question mark - kérdőjel",
		"he's asleep - alszik",
		"accident - baleset",
		"motorway - autópálya",
		"today - ma",
		"yesterday - tegnap",
		"the day before yesterday - tegnapelőtt",
		"potato - burgonya, krumpli",
		"onion - hagyma",
		"goose - liba",
		"turkey - pulyka",
		"Christmas present - karácsonyi ajándék",
		"Christmas carol - karácsonyi ének",
		"a tie - nyakkendő",
		"skull - koponya",
		"too much - túl sokat",
		"to put on weight - hízik",
		"success - siker",
		"to continue - folytatódik",
		"how far from…? - milyen messze … -tól/-től?",
		"a headache - fejfájás",
		"a stomach ache - gyomorfájás",
		"to hurt - fáj"
	],
	[
		"onwards - előre",
		"crack an egg (cracked an egg) - tojást feltörni",
		"scrambled eggs - tojásrántotta",
		"poach (poached) egg - buggyantott tojás",
		"mix (mixed) - kever",
		"pour (poured) - önt",
		"wait (waited) - vár",
		"firm - szilárd",
		"stir (stirred) - megkever",
		"a spatula - szedőlapát",
		"wooden - fából való",
		"plastic - műanyag",
		"a frying pan - serpenyő",
		"a saucepan - lábos",
		"brand-new - vadonatúj",
		"finish - befejeződik",
		"in a hurry - sietve",
		"in a rush - sietve",
		"hurry - hurried - siet",
		"rush (rushed) - siet",
		"spend time (spent time) - időt tölteni",
		"make sure (made sure) - meggyőződik",
		"bomb disposal expert - bombaszakértő",
		"cutlery - evőeszköz",
		"knife - kés",
		"spoon - kanál",
		"salt - só",
		"pepper - bors",
		"sugar - cukor",
		"sweetener - édesítő",
		"what? - mi?",
		"why? - miért?",
		"how long? - mennyi ideig?",
		"who? - ki?",
		"which? - melyik?",
		"blue whale - kék bálna",
		"traffic lights - közlekedési lámpa",
		"free - szabad",
		"slightly - kissé",
		"formal - formális",
		"more formal - formálisabb",
		"fling (flung) - dob",
		"toss (tossed) - hajít",
		"busy - elfoglalt",
		"expect (expected) - számít valamire",
		"what name? - milyen név alatt?",
		"sit down (sat down) - leül",
		"season (seasoned) - fűszerez / ízesít",
		"pick something up - felvesz valamit",
		"shake (shook) - megráz",
		"add - hozzáad",
		"fill (filled) - tölt",
		"bet - fogad",
		"finally - végül",
		"tell (telled) - mond",
		"open (opened) - kinyit",
		"calm down (calmed down) - csillapodik",
		"finish (finished) - befejeződik",
		"drink (drank) - iszik",
		"apple juice - almalé",
		"mineral water - ásványvíz",
		"still mineral water - szénsavmentes ásványvíz",
		"clear (cleared) - leszed",
		"clear away (cleared away) - eltakarít",
		"put (put) - tesz",
		"dishwasher - mosogatógép",
		"turn something on (turned on) - bekapcsol",
		"start (started) - kezd",
		"put back (put back) - visszatesz",
		"a cloth - törlő",
		"wipe (wiped) - töröl",
		"throw away (threw away) - eldob",
		"crumbs - morzsa",
		"outside - kint",
		"a dish - tál",
		"reply (replied) - válaszol",
		"be in a good mood (was in a good mood) - jó kedve van valakinek",
		"catch up with somebody - utolér valakit",
		"sort - fajta",
		"kitchen sink - konyhai mosogató",
		"postman - postás",
		"I'm sure - biztos vagyok benne",
		"hang on! - várj!",
		"hear (head) - hall",
		"deliver (delivered) - kézbesít",
		"an invitation - meghívás",
		"invite - meghív",
		"last chance - utolsó lehetőség",
		"envelope - boríték",
		"Dear Miss Swett - Kedves Swett Kisasszony",
		"offer (offered) - kínál",
		"in my opinion - véleményem szerint",
		"suitableonwards - előre",
		"crack an egg (cracked an egg) - tojást feltörni",
		"scrambled eggs - tojásrántotta",
		"poach (poached) egg - buggyantott tojás",
		"mix (mixed) - kever",
		"pour (poured) - önt",
		"wait (waited) - vár",
		"firm - szilárd",
		"stir (stirred) - megkever",
		"a spatula - szedőlapát",
		"wooden - fából való",
		"plastic - műanyag",
		"a frying pan - serpenyő",
		"a saucepan - lábos",
		"brand-new - vadonatúj",
		"finish - befejeződik",
		"in a hurry - sietve",
		"in a rush - sietve",
		"hurry - hurried - siet",
		"rush (rushed) - siet",
		"spend time (spent time) - időt tölteni",
		"make sure (made sure) - meggyőződik",
		"bomb disposal expert - bombaszakértő",
		"cutlery - evőeszköz",
		"knife - kés",
		"spoon - kanál",
		"salt - só",
		"pepper - bors",
		"sugar - cukor",
		"sweetener - édesítő",
		"what? - mi?",
		"why? - miért?",
		"how long? - mennyi ideig?",
		"who? - ki?",
		"which? - melyik?",
		"blue whale - kék bálna",
		"traffic lights - közlekedési lámpa",
		"free - szabad",
		"slightly - kissé",
		"formal - formális",
		"more formal - formálisabb",
		"fling (flung) - dob",
		"toss (tossed) - hajít",
		"busy - elfoglalt",
		"expect (expected) - számít valamire",
		"what name? - milyen név alatt?",
		"sit down (sat down) - leül",
		"season (seasoned) - fűszerez / ízesít",
		"pick something up - felvesz valamit",
		"shake (shook) - megráz",
		"add - hozzáad",
		"fill (filled) - tölt",
		"bet - fogad",
		"finally - végül",
		"tell (telled) - mond",
		"open (opened) - kinyit",
		"calm down (calmed down) - csillapodik",
		"finish (finished) - befejeződik",
		"drink (drank) - iszik",
		"apple juice - almalé",
		"mineral water - ásványvíz",
		"still mineral water - szénsavmentes ásványvíz",
		"clear (cleared) - leszed",
		"clear away (cleared away) - eltakarít",
		"put (put) - tesz",
		"dishwasher - mosogatógép",
		"turn something on (turned on) - bekapcsol",
		"start (started) - kezd",
		"put back (put back) - visszatesz",
		"a cloth - törlő",
		"wipe (wiped) - töröl",
		"throw away (threw away) - eldob",
		"crumbs - morzsa",
		"outside - kint",
		"a dish - tál",
		"reply (replied) - válaszol",
		"be in a good mood (was in a good mood) - jó kedve van valakinek",
		"catch up with somebody - utolér valakit",
		"sort - fajta",
		"kitchen sink - konyhai mosogató",
		"postman - postás",
		"I'm sure - biztos vagyok benne",
		"hang on! - várj!",
		"hear (head) - hall",
		"deliver (delivered) - kézbesít",
		"an invitation - meghívás",
		"invite - meghív",
		"last chance - utolsó lehetőség",
		"envelope - boríték",
		"Dear Miss Swett - Kedves Swett Kisasszony",
		"offer (offered) - kínál",
		"in my opinion - véleményem szerint",
		"suitable - megfelelő",
		"most suitable - a legmegfelelőbb",
		"candidate - jelölt",
		"security manager - biztonsági igazgató",
		"experience (experienced) - tapasztal",
		"experience - tapasztalat",
		"teach (taught) - tanít",
		"self-defence - önvédelem",
		"combine (combined) - összekapcsol",
		"combination - összeállítás",
		"knowledge - tudás",
		"expert knowledge - szaktudás",
		"officially - hivatalosan",
		"accept (accepted) - elfogad",
		"contact (contaced) - kapcsolatba lép",
		"convenient - kényelmes",
		"congratulate (congratulated) - gratulál",
		"congratulations - gratulálok",
		"well done! - bravó!",
		"interested in - érdekli valami",
		"manager - igazgató",
		"chart - táblázat",
		"save time - időt spórol",
		"save money - pénzt spórol",
		"native speaker - anyanyelvű",
		"square - tér",
		"reserve - reserved - lefoglal",
		"check - checked - ellenőriz",
		"book - lefoglal",
		"look at - megnéz",
		"order - rendel",
		"a pint - 0,568 liter",
		"draugh beer - csapolt sör",
		"chips - hasábburgonya",
		"rare - angolos / véres",
		"medium rare - félig nyers",
		"well-done - teljesen átsült",
		"write something down - wrote down - leír",
		"a toast - pohárköszöntő",
		"at someone's health - iszik valaki egészségére",
		"clink glasses - koccint",
		"topic - téma",
		"topical - aktuális",
		"This isn't what I ordered - Nem ezt rendeltem.",
		"This food is cold. - Ez az étel hideg.",
		"This food doesn't taste fresh. - Ez az étel nem tűnik frissnek.",
		"This food is off. - Ez az étel romlott.",
		"compensate - compensated - kárpótol",
		"megfelelő",
		"most suitable - a legmegfelelőbb",
		"candidate - jelölt",
		"security manager - biztonsági igazgató",
		"experience (experienced) - tapasztal",
		"experience - tapasztalat",
		"teach (taught) - tanít",
		"self-defence - önvédelem",
		"combine (combined) - összekapcsol",
		"combination - összeállítás",
		"knowledge - tudás",
		"expert knowledge - szaktudás",
		"officially - hivatalosan",
		"accept (accepted) - elfogad",
		"contact (contaced) - kapcsolatba lép",
		"convenient - kényelmes",
		"congratulate (congratulated) - gratulál",
		"congratulations - gratulálok",
		"well done! - bravó!",
		"interested in - érdekli valami",
		"manager - igazgató",
		"chart - táblázat",
		"save time - időt spórol",
		"save money - pénzt spórol",
		"native speaker - anyanyelvű",
		"square - tér",
		"reserve - reserved - lefoglal",
		"check - checked - ellenőriz",
		"book - lefoglal",
		"look at - megnéz",
		"order - rendel",
		"a pint - 0,568 liter",
		"draugh beer - csapolt sör",
		"chips - hasábburgonya",
		"rare - angolos / véres",
		"medium rare - félig nyers",
		"well-done - teljesen átsült",
		"write something down - wrote down - leír",
		"a toast - pohárköszöntő",
		"at someone's health - iszik valaki egészségére",
		"clink glasses - koccint",
		"topic - téma",
		"topical - aktuális",
		"This isn't what I ordered - Nem ezt rendeltem.",
		"This food is cold. - Ez az étel hideg.",
		"This food doesn't taste fresh. - Ez az étel nem tűnik frissnek.",
		"This food is off. - Ez az étel romlott.",
		"compensate - compensated - kárpótol"
	],
];

let newPar = document.createElement("p");
newPar.innerText = `${locHashNum*5-4}-${locHashNum*5}. lecke szavai:`;
newPar.style.borderColor = "var(--main-color-theme-primary)";
newPar.style.fontWeight = "500";
content.appendChild(newPar);

if(locHashNum==5 || locHashNum==17){
	let newPar = document.createElement("p");
	newPar.innerText = locHashNum==5 ? "1-20. lecke gyakorlása:" : "21-80. lecke gyakorlása:";
	newPar.style.borderColor = "var(--main-color-theme-primary)";
	newPar.style.borderBottomStyle = "dashed";
	newPar.style.fontWeight = "300";
	content.appendChild(newPar);
}

function addElement(i) {
	let newPar = document.createElement("p");
	newPar.innerText = glossaries[locHashNum][i];
	content.appendChild(newPar);
}

for(let i = 0; i < glossaries[locHashNum].length; i++) {
	addElement(i);
}

if(locHashNum==1){
	selectElement('#menuBackBtn').style.opacity = "0";
	}

	if(locHashNum==18){
	selectElement('#menuForwardBtn').style.opacity = "0";
	}

document.querySelector('#menuBackBtn').addEventListener('click', (e) => {
	prevDef(e);
	if(locHashNum>1){
		window.location.href = '../pages/glossary.html#' + (locHashNum - 1);
		location.reload();
		}
	}
);

selectAnchorSetHref('#menuHomeBtn', '../index.html');

document.querySelector('#menuForwardBtn').addEventListener('click', (e) => {
	prevDef(e);
	if(locHashNum<18){
		window.location.href = '../pages/glossary.html#' + (locHashNum + 1);
		location.reload();
		}
	}
);