let words = [
	[
		{en: "Comfortably", hu: "Kényelmesen"},
	{en: "Good morning", hu: "Jó reggelt!"},
	{en: "Good afternoon", hu: "Jó napot!"},
	{en: "Good evening", hu: "Jó estét!"},
	{en: "Hi", hu: "Szia!"},
	{en: "Hello", hu: "Szia!"},
	{en: "To introduce oneself", hu: "Bemutatkozni"},
	{en: "When?", hu: "Mikor?"},
	{en: "Am", hu: "Délelőtt"},
	{en: "Pm", hu: "Délután"},
	{en: "Five", hu: "Öt"},
	{en: "My name is Gav", hu: "Gavnek hívnak"},
	{en: "Wife", hu: "Feleség"},
	{en: "Husband", hu: "Férj"},
	{en: "Bye", hu: "Viszlát!"},
	{en: "Goodbye", hu: "Viszontlátásra!"},
	{en: "Conversation", hu: "Beszélgetés"},
	{en: "To leave", hu: "Elmenni"},
	{en: "Verb", hu: "Ige"},
	{en: "Easy", hu: "Könnyű"},
	{en: "Hard", hu: "Nehéz"},
	{en: "Numbers 0-10", hu: "Számok 0-10-ig"},
	{en: "Ordinal numbers 1-10", hu: "Sorszámnevek 1-10-ig"},
	{en: "Equals", hu: "Egyenlő"},
	{en: "Days of the week", hu: "A hét napjai"},
	{en: "Months of the year", hu: "Az év hónapjai"},
	{en: "Singular", hu: "Egyes szám"},
	{en: "Plural", hu: "Többes szám"},
	{en: "Result", hu: "Eredmény"},
	{en: "First", hu: "Első"},
	{en: "Last", hu: "Utolsó"},
	{en: "Remember", hu: "Emlékezni"},
	{en: "Good morning", hu: "Jó reggelt!"},
	{en: "Good afternoon", hu: "Jó napot!"},
	{en: "Good evening", hu: "Jó estét!"},
	{en: "Hi", hu: "Szia!"},
	{en: "Hello", hu: "Szia!"},
	{en: "To introduce oneself", hu: "Bemutatkozni"},
	{en: "Octopus", hu: "Polip"},
	{en: "Singular", hu: "Egyes szám"},
	{en: "Plural", hu: "Többes szám"},
	{en: "Student(s)", hu: "Diák(ok)"},
	{en: "When?", hu: "Mikor?"},
	{en: "The alphabet", hu: "ABC"},
	{en: "Letter", hu: "Betű"},
	{en: "To spell", hu: "Betűzni"},
	{en: "How?", hu: "Hogy?/Hogyan?"},
	{en: "Numbers", hu: "Számok"},
	{en: "Ordinal numbers", hu: "Sorszámnevek"},
	{en: "A/an", hu: "egy (határozatlan névelő)"},
	{en: "Normally", hu: "Általában"},
	{en: "Usually", hu: "Rendszerint"},
	{en: "Vowel", hu: "magánhangzó"},
	{en: "Consonant", hu: "mássalhangzó"},
	{en: "Owl", hu: "Bagoly"},
	{en: "Computer", hu: "Számítógép"},
	{en: "Pencil", hu: "Ceruza"},
	{en: "Pen", hu: "Toll"},
	{en: "Keyboard", hu: "Billentyűzet"},
	{en: "Mouse", hu: "Egér"},
	{en: "Girl", hu: "Lány"},
	{en: "Boy", hu: "Fiú"},
	{en: "Aardvark", hu: "Földimalac"},
	{en: "Axe", hu: "Fejsze"},
	{en: "Ear", hu: "Fül"},
	{en: "Knee", hu: "Térd"},
	{en: "Foot", hu: "Lábfej"},
	{en: "Leg", hu: "Láb"},
	{en: "Arm", hu: "Kar"},
	{en: "Eye", hu: "Szem"},
	{en: "Nose", hu: "Orr"},
	{en: "Head", hu: "Fej"},
	{en: "Ostrich", hu: "Strucc"},
	{en: "Pig", hu: "Disznó"},
	{en: "Cow", hu: "Tehén"},
	{en: "Stomach", hu: "Gyomor"},
	{en: "Mouth", hu: "Száj"},
	{en: "Neck", hu: "Nyak"},
	{en: "Shoulder", hu: "Váll"},
	{en: "Chest", hu: "Mellkas"},
	{en: "Thigh", hu: "Comb"},
	{en: "Calf", hu: "Vádli"},
	{en: "Shin", hu: "Sípcsont"},
	{en: "Ankle", hu: "Boka"},
	{en: "Upper arm", hu: "Felkar"},
	{en: "Elbow", hu: "Könyök"},
	{en: "Forearm", hu: "Alkar"},
	{en: "Wrist", hu: "Csukló"},
	{en: "Hand", hu: "Kéz"},
	{en: "Palm", hu: "Tenyér"},
	{en: "Finger", hu: "Ujj"},
	{en: "Thumb", hu: "Hüvelykujj"},
	{en: "Cheek", hu: "Orca"},
	{en: "Chin", hu: "Áll"},
	{en: "Jaw", hu: "Állkapocs"},
	{en: "French", hu: "Francia"},
	{en: "Happy", hu: "Boldog"},
	{en: "Intelligent", hu: "Okos"},
	{en: "Tanned", hu: "Napbarnított"},
	{en: "Married", hu: "Házas"},
	{en: "Single", hu: "Egyedülálló"},
	{en: "Cheap", hu: "Olcsó"},
	{en: "Cold", hu: "Hideg"},
	{en: "Spanish", hu: "Spanyol"},
	{en: "Tall", hu: "Magas"},
	{en: "Ugly", hu: "Csúnya"},
	{en: "Attractive", hu: "Vonzó"},
	{en: "Thirsty", hu: "Szomjas"},
	{en: "Hungry", hu: "Éhes"},
	{en: "Flower", hu: "Virág"},
	{en: "Car", hu: "Autó"},
	{en: "House", hu: "Ház"},
	{en: "Apple", hu: "Alma"},
	{en: "Box", hu: "Doboz"},
	{en: "Bus", hu: "Busz"},
	{en: "Church", hu: "Templom"},
	{en: "Toothbrush", hu: "Fogkefe"},
	{en: "Monkey", hu: "Majom"},
	{en: "Lady", hu: "Hölgy"},
	{en: "Baby", hu: "Csecsemő"},
	{en: "Fly", hu: "Légy"},
	{en: "Knife", hu: "Kés"},
	{en: "Shelf", hu: "Polc"},
	{en: "Wife", hu: "Feleség"},
	{en: "Umbrella", hu: "Esernyő"},
	{en: "Family", hu: "Család"},
	{en: "Boat", hu: "Hajó"},
	{en: "Bicycle", hu: "Bicikli"},
	{en: "Desk", hu: "Íróasztal"},
	{en: "Watch", hu: "Karóra"},
	{en: "Shoe", hu: "Cipő"},
	{en: "Shirt", hu: "Ing"},
	{en: "T-shirt", hu: "Póló"},
	{en: "Sock", hu: "Zokni"},
	{en: "Leaf", hu: "Levél"},
	{en: "Thief", hu: "Tolvaj"},
	{en: "Wolf", hu: "Farkas"},
	{en: "Fat", hu: "Kövér"},
	{en: "Beautiful", hu: "Gyönyörű"},
	{en: "To practise", hu: "Gyakorolni"},
	{en: "Noun", hu: "Főnév"},
	{en: "Different", hu: "Különböző"},
	{en: "Brush", hu: "Kefe"},
	{en: "Remember", hu: "Emlékezni"},
	{en: "Pastry", hu: "Sütemény"},
	{en: "Man", hu: "Férfi"},
	{en: "Child", hu: "Gyerek"},
	{en: "Sheep", hu: "Birka"},
	{en: "Trousers", hu: "Nadrág"},
	{en: "Shorts", hu: "Sort"},
	{en: "Sheep", hu: "Birka"},
	{en: "Glasses", hu: "Szemüveg"},
	{en: "Jeans", hu: "Farmernadrág"},
	{en: "Scissors", hu: "Olló"},
	{en: "Watch", hu: "Karóra"},
	{en: "T-shirt", hu: "Póló"},
	{en: "Ring", hu: "Gyűrű"},
	{en: "Car", hu: "Autó"},
	{en: "House", hu: "Ház"},
	{en: "Helmet", hu: "Sisak"},
	{en: "Skateboard", hu: "Gördeszka"},
	{en: "Elbow pad", hu: "Könyökvédő"},
	{en: "Knee pad", hu: "Terdvédő"},
	{en: "Key", hu: "Kulcs"},
	{en: "Son", hu: "Fiú gyermek"},
	{en: "Daughter", hu: "Lány gyermek"},
	{en: "Squirrel", hu: "Mókus"},
	{en: "Shoelace", hu: "Cipőfűző"},
	{en: "Footballer", hu: "Focista"},
	{en: "Policeman", hu: "Rendőr"},
	{en: "Country", hu: "Ország"},
	{en: "Nationality", hu: "Nemzetiség"},
	{en: "Famous", hu: "Híres"},
	{en: "Object", hu: "Tárgy"},
	{en: "Guitar", hu: "Gitár"},
	{en: "Passport", hu: "Útlevél"},
	{en: "Date of birth", hu: "Születési dátum"},
	{en: "Place of birth", hu: "Születési hely"},
	{en: "Where are you from?", hu: "Honnan való vagy?"},
	{en: "First name", hu: "Keresztnév"},
	{en: "Surname", hu: "Családi név/Vezeték név"},
	{en: "When?", hu: "Mikor?"},
	{en: "What?", hu: "Mit?"},
	{en: "Where?", hu: "Hol? Hova?"},
	{en: "Owner", hu: "Tulajdonos"},
	{en: "Bowl", hu: "Tál"},
	{en: "Tail", hu: "Farok"},
	{en: "Stethoscope", hu: "Sztetoszkóp"},
	{en: "Example", hu: "Példa"},
	{en: "Place", hu: "Hely"},
	{en: "Noon", hu: "Dél"},
	{en: "To improve", hu: "Megjavít"},
	{en: "Probably", hu: "Várható"},
	{en: "Likely", hu: "Valószínű"},
	{en: "Pattern", hu: "Séma"},
	{en: "To spell", hu: "Betűz"},
	{en: "Different", hu: "más"},
	{en: "Black", hu: "Fekete"},
	{en: "White", hu: "Fehér"},
	{en: "Red", hu: "Piros/vörös"},
	{en: "Orange", hu: "Narancsárga"},
	{en: "Yellow", hu: "Sárga"},
	{en: "Green", hu: "Zöld"},
	{en: "Blue", hu: "Kék"},
	{en: "Pink", hu: "Rózsaszín"},
	{en: "Grey", hu: "Szürke"},
	{en: "Brown", hu: "Barna"},
	{en: "Ribbon", hu: "Szalag"},
	{en: "Autumn", hu: "ősz"},
	{en: "Near", hu: "Közel"},
	{en: "Far", hu: "Messze"},
	{en: "Hyphen", hu: "Kötőjel"},
	{en: "Verb", hu: "Ige"},
	{en: "Verbs", hu: "Igék"},
	{en: "To come", hu: "Jön"},
	{en: "To go", hu: "Megy"},
	{en: "To live", hu: "Él"},
	{en: "To work", hu: "Dolgozik"},
	{en: "To read", hu: "Olvas"},
	{en: "To write", hu: "Ír"},
	{en: "To drive", hu: "Vezet"},
	{en: "To Walk", hu: "Sétál"},
	{en: "To run", hu: "Fut"},
	{en: "To swim", hu: "Uszik"},
	{en: "To like", hu: "Kedvel/tetszik"},
	{en: "To love", hu: "Szeret"},
	{en: "To wash", hu: "Mos"},
	{en: "To wake up", hu: "Felébred"},
	{en: "To get up", hu: "Felkel"},
	{en: "To fly", hu: "Repül"},
	{en: "To play", hu: "Játszik"},
	{en: "To carry", hu: "Visz"},
	{en: "Always", hu: "Mindig"},
	{en: "Never", hu: "Soha"},
	{en: "Every day", hu: "Mindennap"},
	{en: "Every Saturday", hu: "Minden szombaton"},
	{en: "Sometimes", hu: "Néha"},
	{en: "Three times a week", hu: "Hetente háromszor"},
	{en: "Every weekend", hu: "Minden hétvégen"},
	{en: "Twice a year", hu: "Évente kétszer"},
	{en: "Usually", hu: "Általában"},
	{en: "Normally", hu: "Általában"},
	{en: "When/when?", hu: "Amikor/Mikor?"},
	{en: "How often?", hu: "Milyen gyakran?"},
	{en: "Nearly always", hu: "Majd nem mindig"},
	{en: "True", hu: "IGAZ"},
	{en: "False", hu: "Nem igaz"},
	{en: "Daily routine", hu: "Napi rutin"},
	{en: "Everything else", hu: "Minden más"},
	{en: "To have a shower", hu: "Zuhanyzik"},
	{en: "To shave", hu: "Borotválkozik"},
	{en: "To dry", hu: "Száritani"},
	{en: "To brush your teeth", hu: "Fogat mos"},
	{en: "To comb", hu: "Fésülködik"},
	{en: "To get dressed", hu: "Felöltözik"},
	{en: "To cook", hu: "Föz"},
	{en: "To drink", hu: "Iszik"},
	{en: "To wash up", hu: "elmosogat"},
	{en: "To put on", hu: "fölvesz"},
	{en: "Parent", hu: "Szüllő"},
	{en: "Parents", hu: "Szüllők"},
	{en: "Grandparent", hu: "Nagyszüllő"},
	{en: "Grandparents", hu: "Nagyszüllők"},
	{en: "Likely", hu: "Valószínű"},
	{en: "Not likely", hu: "Nem valószínű"},
	{en: "To kiss", hu: "Csókol"},
	{en: "To fix/to repair", hu: "Megjavít"},
	{en: "To fish", hu: "Halászik"},
	{en: "Occupation", hu: "Foglolkozás"},
	{en: "Job", hu: "Állás"},
	{en: "Nurse", hu: "Nővér"},
	{en: "Butcher", hu: "Hentes"},
	{en: "Waiter", hu: "Pincér"},
	{en: "Cashier", hu: "Pénztáros"},
	{en: "Shop assistant", hu: "Eladó"},
	{en: "Plumber", hu: "Vízvezeték szerelő"},
	{en: "Bus driver", hu: "Buszvezető"},
	{en: "Librarian", hu: "Könyvtáros"},
	{en: "Dentist", hu: "Fogorvos"},
	{en: "Cleaner", hu: "Takaritó"},
	{en: "Pilot", hu: "Pilóta"},
	{en: "Soldier", hu: "Katona"},
	{en: "Hairdresser", hu: "Fodrász"},
	{en: "Barber", hu: "Borbély"},
	{en: "Architect", hu: "Építész"},
	{en: "To protect", hu: "Megvéd"},
	{en: "To attack", hu: "Támod"},
	{en: "To defend", hu: "Véd"},
	{en: "To bring", hu: "Hoz"},
	{en: "To cut", hu: "Vág"},
	{en: "To find", hu: "Talál"},
	{en: "To start", hu: "Kezd"},
	{en: "To finish", hu: "Befejez"},
	{en: "To plan", hu: "Térvez"},
	{en: "To draw", hu: "Rajzol"},
	{en: "To sell", hu: "Elad"},
	{en: "To use", hu: "Használ"},
	{en: "To connect", hu: "Összeköt/Kapcsol"},
	{en: "To telephone/to phone", hu: "Telefonál"},
	{en: "To clean", hu: "Takarít/tisztít"},
	{en: "To borrow", hu: "Kölcsönkér"},
	{en: "A bill", hu: "Számla"},
	{en: "A gun", hu: "Lőfegyver"},
	{en: "A uniform", hu: "Egyenruha"},
	{en: "A plan", hu: "Térv"},
	{en: "To punch", hu: "Ütni"},
	{en: "Hyphen", hu: "Kötőjel"},
	{en: "Noun", hu: "Főnév"},
	{en: "To revise", hu: "Átnéz"},
	{en: "Singular", hu: "Egyes szám"},
	{en: "Plural", hu: "Többes szám"},
	{en: "Vowel", hu: "Magánhangzó"},
	{en: "Consonant", hu: "Mássalhangzó"},
	{en: "A bowl of", hu: "Egy tál valami"},
	{en: "A bottle", hu: "Egy palack valami"},
	{en: "A can", hu: "Egy doboz valami"},
	{en: "A piece of", hu: "Egy darab valami"},
	{en: "A carton of", hu: "Egy kartondoboz valami"},
	{en: "A slice of", hu: "Egy szelet valami"},
	{en: "A cup of", hu: "Egy csésze valami"},
	{en: "A glass of", hu: "Egy pohár valami"},
	{en: "A list", hu: "Egy lista"},
	{en: "Ordinal number", hu: "Sorszám"},
	{en: "Cardinal number", hu: "Tőszám"},
	{en: "Always", hu: "Mindig"},
	{en: "Never", hu: "Soha"},
	{en: "Every day", hu: "Mindennap"},
	{en: "Every Saturday", hu: "Minden szombaton"},
	{en: "Sometimes", hu: "Néha"},
	{en: "Three times a week", hu: "Hetente háromszor"},
	{en: "Every weekend", hu: "Minden hétvégen"},
	{en: "Twice a year", hu: "Évente kétszer"},
	{en: "Usually", hu: "Általában"},
	{en: "Normally", hu: "Általában"},
	{en: "When/When?", hu: "Amikor/Mikor?"},
	{en: "How often?", hu: "Milyen gyakran?"},
	{en: "To feel", hu: "Érez"},
	{en: "Puppy", hu: "Kiskutya"},
	{en: "Sheep", hu: "Birka"},
	{en: "To pray", hu: "Imádkozik"},
	{en: "To punch", hu: "Üt"},
	{en: "To fix", hu: "Megjavít"},
	{en: "To double", hu: "Megdupláz"},
	{en: "To combine", hu: "Egyesít"},
	{en: "Correct", hu: "Helyes"},
	{en: "nice", hu: "szép"},
	{en: "to get up", hu: "felkelni"},
	{en: "on", hu: "-on, -en, -ön"},
	{en: "under", hu: "alatt"},
	{en: "next to", hu: "mellet"},
	{en: "a page", hu: "lap"},
	{en: "a contract", hu: "szerződés"},
	{en: "to write", hu: "ír"},
	{en: "to sign", hu: "aláír"},
	{en: "ill", hu: "beteg"},
	{en: "hospital", hu: "korház"},
	{en: "favourite", hu: "kedvenc"},
	{en: "city", hu: "város"},
	{en: "news", hu: "hír"},
	{en: "hero", hu: "hős"},
	{en: "happy", hu: "boldog"},
	{en: "strange", hu: "furcsa"},
	{en: "hole", hu: "lyuk"},
	{en: "motorway", hu: "autópálya"},
	{en: "to study", hu: "tanul"},
	{en: "doctor", hu: "orvos"},
	{en: "dentist", hu: "fogorvos"},
	{en: "hairdresser", hu: "fodrász"},
	{en: "beautician", hu: "kozmetikus"},
	{en: "train", hu: "vonat"},
	{en: "bus", hu: "busz"},
	{en: "party", hu: "buli"},
	{en: "airport", hu: "repülőtér"},
	{en: "train station", hu: "pályaudvar"},
	{en: "bus station", hu: "buszpályaudvar"},
	{en: "police station", hu: "rendőrőrs"},
	{en: "floor", hu: "padló/emelet"},
	{en: "ground floor", hu: "földszint"},
	{en: "1st floor", hu: "első emelet"},
	{en: "2nd floor", hu: "második emelet"},
	{en: "on the 78th floor", hu: "a 78. emeleten"},
	{en: "full", hu: "tele"},
	{en: "tram", hu: "villamos"},
	{en: "adjective-opposite", hu: "melléknév ellentéte"},
	{en: "to describe", hu: "leír"},
	{en: "appearance", hu: "külső megjelenés"},
	{en: "what somebody looks like", hu: "hogy néz ki valaki"},
	{en: "very", hu: "nagyon"},
	{en: "to wear", hu: "visel"},
	{en: "clothes", hu: "ruha"},
	{en: "a suit", hu: "öltöny"},
	{en: "a uniform", hu: "egyenruha"},
	{en: "trousers", hu: "nadrág"},
	{en: "jeans", hu: "farmernadrág"},
	{en: "tights", hu: "harisnyanadrág"},
	{en: "socks", hu: "zokni"},
	{en: "dress", hu: "ruha"},
	{en: "shoes", hu: "cipő"},
	{en: "jumper", hu: "pulóver"},
	{en: "t-shirt", hu: "póló"},
	{en: "shirt", hu: "ing"},
	{en: "middle-aged", hu: "középkorú"},
	{en: "bald", hu: "kopasz"},
	{en: "to modify", hu: "módosít"},
	{en: "to change", hu: "változik/változtat"},
	{en: "power", hu: "erő"},
	{en: "to describe", hu: "leír"},
	{en: "clothes", hu: "ruha"},
	{en: "to modify", hu: "modosít"},
	{en: "to change", hu: "vátozik"},
	{en: "first name", hu: "keresztnév"},
	{en: "surname", hu: "családi név"},
	{en: "maiden name", hu: "lánykori név"},
	{en: "bald", hu: "kopasz"},
	{en: "to marry", hu: "házosodik"},
	{en: "single", hu: "egyedülálló"},
	{en: "beige", hu: "bézs"},
	{en: "a belt", hu: "öv"},
	{en: "middle-aged", hu: "középkorú"},
	{en: "walking stick", hu: "sétabot"},
	{en: "father-in-law", hu: "após"},
	{en: "mother-in-law", hu: "anyós"},
	{en: "son-in-law", hu: "vej"},
	{en: "daugter-in-law", hu: "meny"},
	{en: "brother-in-law", hu: "sógor"},
	{en: "sister-in-law", hu: "sógornő"},
	{en: "grandparent", hu: "nagyszülő"},
	{en: "grandparents", hu: "nagyszülők"},
	{en: "grandchild", hu: "unoka"},
	{en: "grandson", hu: "fiúunoka"},
	{en: "granddaughter", hu: "lányunoka"},
	{en: "relationship", hu: "kapcsolat"},
	{en: "closer", hu: "közelebb"},
	{en: "beside", hu: "mellet"},
	{en: "next to", hu: "mellet"},
	{en: "opposite", hu: "szemben lévő"},
	{en: "beside", hu: "mellett"},
	{en: "next to", hu: "mellett"},
	{en: "between", hu: "között"},
	{en: "in front of", hu: "vmi előtt"},
	{en: "behind", hu: "mögött"},
	{en: "above", hu: "vmi felett"},
	{en: "below", hu: "vmi alatt"},
	{en: "approximately", hu: "körülbelül"},
	{en: "-ish", hu: "köreülbelül"},
	{en: "trainers", hu: "tornacipő"},
	{en: "fridge", hu: "hűtőszekrény"},
	{en: "freezer", hu: "fagyasztó"},
	{en: "some", hu: "néhány"},
	{en: "frozen", hu: "fagyasztott"},
	{en: "refrigerated", hu: "hűtőtt"},
	{en: "sentence", hu: "mondat"},
	{en: "correct", hu: "helyes"},
	{en: "incorrect", hu: "helytelen"}
],
	[
		{en: "to come", hu: "jön"},
{en: "to go", hu: "megy"},
{en: "to live", hu: "él"},
{en: "to work", hu: "dolgozik"},
{en: "to read", hu: "olvas"},
{en: "to write", hu: "ír"},
{en: "to drive", hu: "vezet"},
{en: "to walk", hu: "sétál"},
{en: "to run", hu: "fut"},
{en: "to swim", hu: "uszik"},
{en: "to like", hu: "kedvel/tetszik"},
{en: "to love", hu: "szeret"},
{en: "to wash", hu: "mos"},
{en: "to wake up", hu: "felébred"},
{en: "to get up", hu: "felkel"},
{en: "to fly", hu: "repül"},
{en: "to play", hu: "játszik"},
{en: "to carry", hu: "visz"},
{en: "always", hu: "mindig"},
{en: "never", hu: "soha"},
{en: "every day", hu: "mindennap"},
{en: "every saturday", hu: "minden szombaton"},
{en: "sometimes", hu: "néha"},
{en: "three times a week", hu: "hetente háromszor"},
{en: "every weekend", hu: "minden hétvégen"},
{en: "twice a year", hu: "évente kétszer"},
{en: "usually", hu: "általában"},
{en: "normally", hu: "általában"},
{en: "always", hu: "mindig"},
{en: "nearly always", hu: "majd nem mindig"},
{en: "true", hu: "igaz"},
{en: "false", hu: "nem igaz"},
{en: "butcher", hu: "hentes"},
{en: "nurse", hu: "nővér"},
{en: "soldier", hu: "katona"},
{en: "dentist", hu: "fogorvos"},
{en: "cleaner", hu: "takaritó"},
{en: "bus driver", hu: "autóbuszvezető"},
{en: "shop assistant", hu: "eladó"},
{en: "waiter", hu: "pincer"},
{en: "to cut", hu: "vág"},
{en: "meat", hu: "hús"},
{en: "to help", hu: "segít"},
{en: "to defend", hu: "véd"},
{en: "to look after", hu: "gondoskodik"},
{en: "to clean", hu: "takarít"},
{en: "a building", hu: "épület"},
{en: "to drive", hu: "vezet"},
{en: "to sell", hu: "elad"},
{en: "thing", hu: "dolog"},
{en: "to bring", hu: "hoz"},
{en: "a drink", hu: "egy ital"},
{en: "food", hu: "étel"},
{en: "to pronounce", hu: "kiejt"},
{en: "pronunciation", hu: "kiejtés"},
{en: "ability", hu: "képeség"},
{en: "possible", hu: "lehetséges"},
{en: "not possible", hu: "nem lehetséges"},
{en: "impossible", hu: "lehetetlen"},
{en: "polite", hu: "udvarias"},
{en: "impolite", hu: "udvariatlan"},
{en: "rude (very impolite)", hu: "goromba"},
{en: "of course", hu: "természetesen"},
{en: "to receive", hu: "kap"},
{en: "to get", hu: "kap"},
{en: "a question", hu: "kérdés"},
{en: "an answer", hu: "válasz"},
{en: "to ask a question", hu: "kérdez"},
{en: "to reply", hu: "válaszol"},
{en: "just a moment", hu: "egy pillanat"},
{en: "to compare", hu: "összehasonlít"},
{en: "a comparison", hu: "összehasonlítás"},
{en: "same", hu: "ugyanaz"},
{en: "similar", hu: "hasanló"},
{en: "different", hu: "különböző"},
{en: "to spot", hu: "észrevész"},
{en: "like", hu: "tetszik"},
{en: "love", hu: "szeret"},
{en: "want", hu: "akar"},
{en: "need", hu: "szüksége van"},
{en: "know", hu: "tud"},
{en: "understand", hu: "ért"},
{en: "remember", hu: "emlékszik"},
{en: "forget", hu: "elfelejt"},
{en: "prefer", hu: "jobban tetszik"},
{en: "hate", hu: "gyűlöl"},
{en: "mean", hu: "gondol"},
{en: "believe", hu: "hisz"},
{en: "hammer", hu: "kalapács"},
{en: "sideburns", hu: "pajesz"},
{en: "to fight", hu: "harcol"},
{en: "crime fighter", hu: "bűnezésellen harcos"},
{en: "superhero", hu: "szuperhős"},
{en: "to exercise", hu: "edz"},
{en: "to work out (synonym for exercise)", hu: "edz"},
{en: "permanent", hu: "állandó"},
{en: "temporary", hu: "átmeneti"},
{en: "always", hu: "mindig"},
{en: "never", hu: "soha"},
{en: "sometimes", hu: "néha"},
{en: "usually", hu: "általában"},
{en: "often", hu: "gyakran"},
{en: "occupation", hu: "foglalkozás"},
{en: "job", hu: "állás"},
{en: "cocktail", hu: "koktél"},
{en: "unicorn", hu: "egyszarvú"},
{en: "parrot", hu: "papagai"},
{en: "horse", hu: "ló"},
{en: "cheetah", hu: "gepárd"},
{en: "kangaroo", hu: "kengurú"},
{en: "elephant", hu: "elefánt"},
{en: "frog", hu: "béka"},
{en: "fly", hu: "légy"},
{en: "wing", hu: "szárny"},
{en: "to kill", hu: "öl"},
{en: "to destroy", hu: "elpusztít"},
{en: "a planet", hu: "bolygó"},
{en: "a magazine", hu: "magazin"},
{en: "a magazine cover", hu: "címlap"},
{en: "it's raining", hu: "esik az eső"},
{en: "street", hu: "utca"},
{en: "wet", hu: "vizes"},
{en: "to fall", hu: "esni"},
{en: "sky", hu: "ég"},
{en: "puddle", hu: "tócsa"},
{en: "umbrella", hu: "esernyő"},
{en: "windscreen wipers", hu: "ablaktörlő"},
{en: "mask", hu: "álarc"},
{en: "shoulder pad", hu: "válltömés"},
{en: "top", hu: "felső"},
{en: "strong", hu: "erős"},
{en: "biceps", hu: "bicepsz"},
{en: "haircut", hu: "frizura"},
{en: "like", hu: "tetszik"},
{en: "love", hu: "szeret"},
{en: "want", hu: "akar"},
{en: "need", hu: "szüksége van"},
{en: "know", hu: "tud"},
{en: "understand", hu: "ért"},
{en: "remember", hu: "emlékszik"},
{en: "forget", hu: "elfelejt"},
{en: "prefer", hu: "jobban tetszik"},
{en: "hate", hu: "gyűlöl"},
{en: "mean", hu: "gondol"},
{en: "believe", hu: "hisz"},
{en: "sibling", hu: "testvér"},
{en: "boot", hu: "csizma/bakancs"},
{en: "ankle", hu: "boka"},
{en: "uncle", hu: "nagybátya"},
{en: "aunt", hu: "nagynéni"},
{en: "nephew", hu: "unokaöcs"},
{en: "niece", hu: "unokahúg"},
{en: "to compare", hu: "ősszehasonlít"},
{en: "similarity", hu: "hasonlóság"},
{en: "difference", hu: "különbség"},
{en: "petrol", hu: "benzin"},
{en: "cheap", hu: "olcsó"},
{en: "petrol station", hu: "benzinkút"},
{en: "remote control", hu: "távirányitó"},
{en: "to make a decision", hu: "dönteni"},
{en: "old", hu: "öreg / idős"},
{en: "older", hu: "öregebb / idősebb"},
{en: "young", hu: "fiatal"},
{en: "younger", hu: "fiatalabb"},
{en: "short", hu: "alacsony (személy) / rövid"},
{en: "shorter", hu: "alacsonyabb (személy) / rövidebb"},
{en: "happy", hu: "boldog"},
{en: "happier", hu: "boldogabb"},
{en: "easy", hu: "könnyű"},
{en: "easier", hu: "könnyebb"},
{en: "early", hu: "korán/korai"},
{en: "earlier", hu: "korábban/korábbi"},
{en: "careful", hu: "óvatos"},
{en: "more careful", hu: "óvatasabb"},
{en: "expensive", hu: "drága"},
{en: "more expensive", hu: "drágább"},
{en: "interesting", hu: "érdekes"},
{en: "more interesting", hu: "érdekesseb"},
{en: "good", hu: "jó"},
{en: "well", hu: "jól"},
{en: "better", hu: "jobb"},
{en: "bad", hu: "rossz"},
{en: "worse", hu: "rosszabb"},
{en: "old", hu: "older"},
{en: "large", hu: "larger"},
{en: "strong", hu: "stronger"},
{en: "modern", hu: "more modern"},
{en: "intelligent", hu: "more intelligent"},
{en: "old", hu: "régi / öreg"},
{en: "older", hu: "régibb / öregebb"},
{en: "large", hu: "nagy"},
{en: "larger", hu: "nagyobb"},
{en: "strong", hu: "erős"},
{en: "stronger", hu: "erősebb"},
{en: "modern", hu: "korszerű"},
{en: "more modern", hu: "korszerűbb"},
{en: "intelligent", hu: "intelligens"},
{en: "more intelligent", hu: "intelligensebb"},
{en: "easy", hu: "könnyű"},
{en: "hard", hu: "nehéz"},
{en: "easier", hu: "könnyebb"},
{en: "harder / more difficult", hu: "nehezebb"},
{en: "cold", hu: "hideg"},
{en: "hot", hu: "forró"},
{en: "colder", hu: "hidegebb"},
{en: "hotter", hu: "forró"},
{en: "good", hu: "jó"},
{en: "bad", hu: "rossz"},
{en: "better", hu: "jobb"},
{en: "worse", hu: "rosszabb"},
{en: "grandparent", hu: "nagyszülő"},
{en: "grandparents", hu: "nagyszülők"},
{en: "grandchild", hu: "unoka"},
{en: "grandson", hu: "fiúunoka"},
{en: "granddaughter", hu: "lányunoka"},
{en: "father-in-law", hu: "após"},
{en: "mother-in-law", hu: "anyós"},
{en: "son-in-law", hu: "vej"},
{en: "daughter-in-law", hu: "meny"},
{en: "piffle", hu: "szamárság"},
{en: "luck", hu: "szerencse"},
{en: "lucky", hu: "szerencsés"},
{en: "unlucky", hu: "szerencsétlen"},
{en: "certain", hu: "biztos"},
{en: "to introduce", hu: "bemutat"},
{en: "question mark", hu: "kérdőjel"},
{en: "question", hu: "kérdés"},
{en: "a uniform", hu: "egyenruha"},
{en: "he's asleep", hu: "alszik"},
{en: "accident", hu: "baleset"},
{en: "motorway", hu: "autópálya"},
{en: "today", hu: "ma"},
{en: "yesterday", hu: "tegnap"},
{en: "the day before yesterday", hu: "tegnapelőtt"},
{en: "tomorrow", hu: "holnap"},
{en: "the day after tomorrow", hu: "holnapután"},
{en: "swift", hu: "gyors"},
{en: "swiftly", hu: "gyorsan"},
{en: "confident", hu: "magabiztos"},
{en: "to jump", hu: "ugrik"},
{en: "place", hu: "hely"},
{en: "movement", hu: "mozgás"},
{en: "ATM", hu: "bankautomata"},
{en: "lock", hu: "zár"},
{en: "to open", hu: "kinyit"},
{en: "to put into gear", hu: "sebességbe kapcsol"},
{en: "would you like?", hu: "szeretne?"},
{en: "want", hu: "akar"},
{en: "what would you like?", hu: "Mit szeretne?"},
{en: "What do you want?", hu: "Mit akarsz?"},
{en: "polite", hu: "udvarias"},
{en: "impolite", hu: "udvariatlan"},
{en: "rude", hu: "goromba"},
{en: "awful", hu: "szörnyű"},
{en: "terrible", hu: "borzasztó"},
{en: "horrible", hu: "rémes"},
{en: "deaf", hu: "süket"},
{en: "staff", hu: "személyzet"},
{en: "to offer", hu: "kinál/ajánl"},
{en: "nice", hu: "kedves"},
{en: "popular", hu: "népszerű"},
{en: "unpopular", hu: "népszerűtlen"},
{en: "general", hu: "általános"},
{en: "specific", hu: "konkrét"},
{en: "to work", hu: "dolgozik"},
{en: "to record", hu: "felvesz"},
{en: "to watch", hu: "figyel"},
{en: "to bake", hu: "süt"},
{en: "to copy", hu: "másol"},
{en: "to carry", hu: "visz"},
{en: "to marry", hu: "házasodik"},
{en: "to study", hu: "tanul"},
{en: "a winery", hu: "borászat"},
{en: "a cellar", hu: "pince"},
{en: "dinner", hu: "vacsora"},
{en: "A restaurant", hu: "étterem"},
{en: "pork", hu: "disznóhús"},
{en: "chicken", hu: "csirke"},
{en: "spinach", hu: "spenót"},
{en: "pumpkin", hu: "tök"},
{en: "mashed potato", hu: "krumplipüré"},
{en: "to begin", hu: "kezd"},
{en: "to buy", hu: "vesz"},
{en: "to drink", hu: "iszik"},
{en: "to eat", hu: "eszik"},
{en: "to forget", hu: "elfelejt vmit"},
{en: "to find", hu: "talál"},
{en: "to give", hu: "ad"},
{en: "to go", hu: "megy"},
{en: "to pay", hu: "fizet"},
{en: "to put", hu: "rak"},
{en: "to read", hu: "olvas"},
{en: "to say", hu: "mond"},
{en: "to speak", hu: "beszél"},
{en: "to stand", hu: "áll"},
{en: "to think", hu: "gondol"},
{en: "potato", hu: "burgonya"},
{en: "onion", hu: "hagyma"},
{en: "goose", hu: "liba"},
{en: "turkey", hu: "pulyka"},
{en: "Christmas present", hu: "karácsonyi ajándék"},
{en: "Christmas carol", hu: "ének"},
{en: "a tie", hu: "nyakkendő"},
{en: "skull", hu: "koponya"},
{en: "gloves", hu: "kesztyű"},
{en: "wooly hat", hu: "kötött sapka"},
{en: "to wrap", hu: "csomagol"},
{en: "to decorate", hu: "díszit"},
{en: "vegetables", hu: "zöldség"},
{en: "carrot", hu: "sárgarépa"},
{en: "Brussels sprout", hu: "kellbimbó"},
{en: "cabbage", hu: "káposzta"},
{en: "meat", hu: "hús"},
{en: "goose leg", hu: "libacomb"},
{en: "garlic", hu: "fokhagyma"},
{en: "to buy - bought", hu: "vesz"},
{en: "to bring - brought", hu: "hoz"},
{en: "recipe", hu: "recept"},
{en: "ingredients", hu: "összetevők/hozzávalók"},
{en: "flour", hu: "liszt"},
{en: "bicarbonate of soda", hu: "szódabikárbóna"},
{en: "teaspoon", hu: "teáskanál"},
{en: "table spoon", hu: "evőkanál"},
{en: "ginger", hu: "gyömbér"},
{en: "to grind - gound", hu: "őröl"},
{en: "ground", hu: "őrölt"},
{en: "cinnamon", hu: "fahéj"},
{en: "I don't know", hu: "Nem tudom"},
{en: "I don't care", hu: "Nem érdekel"},
{en: "to forget - forgot", hu: "elfeléjt"},
{en: "not important", hu: "nem fontos"},
{en: "egg", hu: "tojás"},
{en: "to lay an egg", hu: "tojást tojni"},
{en: "fried egg", hu: "tükörtojás"},
{en: "molasses", hu: "mélasz"},
{en: "viscous", hu: "nyúlos"},
{en: "sieve", hu: "szita"},
{en: "to sift - sifted", hu: "szitál"},
{en: "food mixer", hu: "konyhai robotgép"},
{en: "to mix", hu: "kever"},
{en: "to rub", hu: "dörsöl"},
{en: "to collect", hu: "összegyűlik"},
{en: "to throw", hu: "dob"},
{en: "breadcrumbs", hu: "morzsa"},
{en: "fork", hu: "villa"},
{en: "whisk", hu: "habverő"},
{en: "rolling pin", hu: "sodrófa"},
{en: "to confuse - confused", hu: "összezavar"},
{en: "confused", hu: "zavart"},
{en: "to celebrate", hu: "ünnepel"},
{en: "a source", hu: "forrás"},
{en: "Religious festival", hu: "vallási ünnep"},
{en: "the day before", hu: "előző nap"},
{en: "to play", hu: "játszik"},
{en: "to prepare", hu: "készít"},
{en: "to organise", hu: "szervez"},
{en: "to turn on", hu: "bekapcsol"},
{en: "to turn off", hu: "kikapcsol"},
{en: "a hob", hu: "főzőlap"},
{en: "an oven", hu: "sütő"},
{en: "important", hu: "fontos"},
{en: "stress", hu: "stressz"},
{en: "naturally", hu: "természetesen"},
{en: "tradition", hu: "hagyomány"},
{en: "traditionally", hu: "hagyonmányosan"},
{en: "it depends", hu: "attól függ"},
{en: "tree trunnk", hu: "fatörzs"},
{en: "fairy lights", hu: "karácsonyi égők"},
{en: "Christmas songs", hu: "karácsonyi dalok"},
{en: "nasty", hu: "komisz"},
{en: "a miser", hu: "fösvény"},
{en: "to spend", hu: "költ"},
{en: "to hate", hu: "gyűlöl"},
{en: "to collect", hu: "gyűjt"},
{en: "pots of money", hu: "nagyon sok pénz"},
{en: "huge amounts of cash", hu: "készpénz rengetek mennyiségben"},
{en: "old", hu: "öreg"},
{en: "candle", hu: "gyertya"},
{en: "a money-lender", hu: "hitelező"},
{en: "a usurer", hu: "uzsora"},
{en: "to charge interest", hu: "kamatot felszámít"},
{en: "fair", hu: "tiszteséges"},
{en: "to exploit", hu: "kihasznál"},
{en: "nice", hu: "kedves"},
{en: "to check", hu: "elenőriz"},
{en: "on time", hu: "időben"},
{en: "to be late", hu: "késik"},
{en: "to deduct", hu: "levon"},
{en: "salt", hu: "só"},
{en: "lunchtime", hu: "ebédidő"},
{en: "toilet paper", hu: "WC papír"},
{en: "day off", hu: "szabadnap"},
{en: "to count", hu: "számol"},
{en: "a ghost", hu: "szellem"},
{en: "almost", hu: "majdnem"},
{en: "to wet the bed", hu: "az ágyba vízelni"},
{en: "business", hu: "cég"},
{en: "to be nice", hu: "kedves lenni"},
{en: "to spend", hu: "költ"},
{en: "for ever and ever", hu: "örökké"},
{en: "to show", hu: "mutat"},
{en: "portable", hu: "hordazható"},
{en: "to remind", hu: "emlékeztet"},
{en: "a girlfriend", hu: "barátnő"},
{en: "a boss", hu: "főnök"},
{en: "to leave", hu: "elmegy"},
{en: "to arrive", hu: "érkezik"},
{en: "dead", hu: "halott"},
{en: "to die", hu: "meghal"},
{en: "nobody", hu: "senki"},
{en: "to visit", hu: "látogat"},
{en: "a grave", hu: "sír"},
{en: "upset", hu: "felizgatatt"},
{en: "to feel", hu: "érez"},
{en: "a couple", hu: "pár"},
{en: "happy", hu: "boldog"},
{en: "to go to sleep - went to sleep", hu: "elalszik"},
{en: "to wake up - woke up", hu: "felébred"},
{en: "mean", hu: "fukar"},
{en: "stingy", hu: "fukar"},
{en: "horrible", hu: "szörnyű"},
{en: "expensive", hu: "drága"},
{en: "to rush - rushed", hu: "rohan"},
{en: "surprised", hu: "meglepődött"},
{en: "a present", hu: "ajándék"},
{en: "lyrics", hu: "dalszöveg"},
{en: "title", hu: "cím"},
{en: "weird", hu: "furcsa"},
{en: "partridge", hu: "fogoly"},
{en: "pear tree", hu: "körtefa"},
{en: "turtle-dove", hu: "gerle"},
{en: "blackbird", hu: "rigó"},
{en: "ring", hu: "gyűrű"},
{en: "gold", hu: "arany"},
{en: "who cares?", hu: "kit érdekel?"},
{en: "to lay an egg", hu: "tojást tojik"},
{en: "rhythm", hu: "ritmus"},
{en: "swan", hu: "hattyú"},
{en: "maid", hu: "leány"},
{en: "to leap", hu: "ugrik"},
{en: "kangaroo", hu: "kenguru"},
{en: "rabbit", hu: "nyúl"},
{en: "grasshopper", hu: "szöcske"},
{en: "piper", hu: "dudás"},
{en: "bagpipes", hu: "duda"},
{en: "a drummer", hu: "dobos"},
{en: "to drum", hu: "dobol"},
{en: "chat", hu: "cseveg;s"},
{en: "reason", hu: "ok"},
{en: "to fill", hu: "tölt"},
{en: "air", hu: "levegő"},
{en: "crescendo", hu: "fokozatos erősödés"},
{en: "to imagine - imagined", hu: "elképzel"},
{en: "stage", hu: "színpad"},
{en: "microphone", hu: "mikrofon"},
{en: "loudspeaker", hu: "hangszóró"},
{en: "lung(s)", hu: "tödő(k)"},
{en: "audience", hu: "közönség"},
{en: "ceiling", hu: "plafon"},
{en: "curly", hu: "göndör"},
{en: "straight", hu: "egyenes"},
{en: "quiet", hu: "csendes"},
{en: "loud", hu: "hangos"},
{en: "louder", hu: "hangosabb"},
{en: "to sing", hu: "énekel"},
{en: "to release", hu: "kienged"},
{en: "to damage", hu: "megkárosít"},
{en: "too much", hu: "túl sokat"},
{en: "to put on weight", hu: "hízik"},
{en: "success", hu: "siker"},
{en: "stomach", hu: "gyomor"},
{en: "permission", hu: "engedély"},
{en: "to compare", hu: "összehasonlít"},
{en: "a comparison", hu: "összehasonlítás"},
{en: "hopefully", hu: "remélhetőleg"},
{en: "to recover", hu: "felépül"},
{en: "relaxed", hu: "kipihent"},
{en: "refreshed", hu: "felfrissült"},
{en: "uncle", hu: "nagybátya"},
{en: "aunt", hu: "nagynéni"},
{en: "nephew", hu: "unokaöcs"},
{en: "niece", hu: "unokahúg"},
{en: "happy", hu: "boldog"},
{en: "happier", hu: "boldogabb"},
{en: "easy", hu: "könnyű"},
{en: "easier", hu: "könnyebb"},
{en: "early", hu: "korán/korai"},
{en: "earlier", hu: "korábban/korábbi"},
{en: "careful", hu: "óvatos"},
{en: "more careful", hu: "óvatosabb"},
{en: "expensive", hu: "drága"},
{en: "more expensive", hu: "drágább"},
{en: "interesting", hu: "érdekes"},
{en: "more interesting", hu: "érdekesebb"},
{en: "good", hu: "jó"},
{en: "well", hu: "jól"},
{en: "better", hu: "jobb"},
{en: "bad", hu: "rossz"},
{en: "worse", hu: "rosszabb"},
{en: "awful", hu: "szörnyű"},
{en: "to continue", hu: "folytatódik"},
{en: "-ish", hu: "körülbelül"},
{en: "how far from…?", hu: "milyen messze …tól/től?"},
{en: "a headache", hu: "fejfájás"},
{en: "A stomach ache", hu: "gyomorfájás"},
{en: "to hurt", hu: "fáj"},
{en: "to ache", hu: "fáj"},
{en: "painful", hu: "fájdalmos"},
{en: "a hangover", hu: "másnaposság"},
{en: "to be hung-over", hu: "másnapos"},
{en: "to have a cold", hu: "meg van fázva"},
{en: "an infection", hu: "fertőzés"},
{en: "blocked", hu: "eldugult"},
{en: "to sneeze", hu: "tüsszent"},
{en: "damp", hu: "nedves"},
{en: "wet", hu: "vizes"},
{en: "soaking wet", hu: "bőrig ázott"},
{en: "to be in the doghouse", hu: "büntetésben van"},
{en: "eccentric", hu: "különc"},
{en: "elegant", hu: "elegáns"},
{en: "ecelctic", hu: "eklektikus"},
{en: "electric eel", hu: "elektromos angola"},
{en: "to pay attention", hu: "figyelni"},
{en: "type", hu: "típus"},
{en: "yellow-ish", hu: "sárgás"},
{en: "carbonated", hu: "szénsavas"},
{en: "bubbles", hu: "buborék"},
{en: "phrase", hu: "kifejezés"},
{en: "useful", hu: "hasznos"},
{en: "polite", hu: "udvarias"},
{en: "to order", hu: "rendel"},
{en: "a pint of beer", hu: "1 korsó sör"},
{en: "a 1/2 pint of beer", hu: "1 pohár sör"},
{en: "shandy", hu: "radler"},
{en: "lemonade", hu: "szénsavas limonádé"},
{en: "table service", hu: "kiszolgálás az asztálnál"},
{en: "counter service", hu: "kiszolgálás a pultnál"},
{en: "to tip", hu: "borravalót adni"},
{en: "a tip", hu: "borravaló"},
{en: "to finish", hu: "befejez"},
{en: "a bench", hu: "pad"},
{en: "to fall asleep", hu: "elalszik"},
{en: "wetter than", hu: "vizessebb mint…"},
{en: "to cough", hu: "köhög"},
{en: "to sneeze", hu: "tüsszent"},
{en: "to have a sore throat", hu: "faj a torka"},
{en: "to have a blocked nose", hu: "eldugult az orra"},
{en: "rabies", hu: "veszettség"},
{en: "originally", hu: "eredetileg"},
{en: "disease", hu: "betegség"},
{en: "often", hu: "gyakran"},
{en: "better", hu: "jobb"},
{en: "to convince", hu: "meggyőz"},
{en: "to realize", hu: "észrevesz"},
{en: "to decide", hu: "dönt"},
{en: "to offer", hu: "kínál/felajánl"},
{en: "to catch a cold", hu: "megfázik"},
{en: "situation", hu: "helyzet"},
{en: "realise", hu: "észrevesz"},
{en: "I'm sorry", hu: "sajnálom"},
{en: "to behave", hu: "viselkedik"},
{en: "badly", hu: "rosszul"},
{en: "to forgive", hu: "megbocsát"},
{en: "to accept", hu: "elfogad"},
{en: "the matter is closed", hu: "az ügy le van zárva"},
{en: "excuse me!", hu: "elnézést kérek!"},
{en: "Sorry!", hu: "Bocsánot!"},
{en: "to move", hu: "mozog"},
{en: "to get someone's attention", hu: "valakinek a figyelmet felhívni"},
{en: "to wave", hu: "int"},
{en: "a crowd", hu: "tömeg"},
{en: "to force", hu: "erőszakol"},
{en: "to pass", hu: "elhalad"},
{en: "to interrupt", hu: "félbeszakit"},
{en: "to miss", hu: "lemarad"},
{en: "to celebrate", hu: "ünnepel"},
{en: "celebration", hu: "ünneplés"},
{en: "noun", hu: "főnév"},
{en: "adjective", hu: "melléknév"},
{en: "adverb", hu: "határozószó"},
{en: "how", hu: "hogy/hogyan"},
{en: "quickly", hu: "gyorsan"},
{en: "slowly", hu: "lassan"},
{en: "opposite", hu: "ellentéte"},
{en: "to add", hu: "hozzáad"},
{en: "to provide", hu: "nyújt"},
{en: "thief", hu: "tolvaj"},
{en: "similar", hu: "hasonló"},
{en: "together", hu: "együtt"},
{en: "a couple", hu: "pár"},
{en: "automatically", hu: "automatikusan"},
{en: "extra", hu: "plussz"},
{en: "nice", hu: "szép"},
{en: "neat", hu: "rendezett"},
{en: "a mistake", hu: "egy hiba"},
{en: "to spell", hu: "betűz"},
{en: "quick", hu: "gyors"},
{en: "quickly", hu: "gyorsan"},
{en: "bad", hu: "rossz"},
{en: "badly", hu: "rosszul"},
{en: "easy", hu: "könnyű"},
{en: "easily", hu: "könnyen"},
{en: "heavy", hu: "nehéz"},
{en: "heavily", hu: "nehézen"},
{en: "awkward", hu: "kellemetlen"},
{en: "to accelerate", hu: "gyorsul"},
{en: "to bark", hu: "ugat"},
{en: "quiet", hu: "csendes"},
{en: "quietly", hu: "csendesen"},
{en: "loud", hu: "hangos"},
{en: "loudly", hu: "hangosan"},
{en: "a blocked nose", hu: "eldugult orr"},
{en: "a runny nose", hu: "folyik az orr"},
{en: "liquid", hu: "folyadék"},
{en: "a tissue", hu: "papír zsebkendő"},
{en: "to cough", hu: "köhög"},
{en: "to sneeze", hu: "tüsszent"},
{en: "lucky", hu: "szerencsés"},
{en: "unlucky", hu: "szerencsétlen"},
{en: "to have a temperature", hu: "valakinek láza van"},
{en: "fever", hu: "láz"},
{en: "to bump into", hu: "összefut valakivel"},
{en: "earache", hu: "fülfájás"},
{en: "toothache", hu: "fogfájás"},
{en: "backache", hu: "hátfájás"},
{en: "lumbago", hu: "lumbágó"},
{en: "to break", hu: "tör"},
{en: "broken", hu: "törött"},
{en: "leg", hu: "láb"},
{en: "arm", hu: "kar"},
{en: "finger", hu: "ujj"},
{en: "back", hu: "hát/derék"},
{en: "ankle", hu: "boka"},
{en: "I feel sick", hu: "rosszul vagyok/hányingerem van"},
{en: "to vomit", hu: "hány"},
{en: "to bump into", hu: "összefut valakivel"},
{en: "a job interview", hu: "állás interjú"},
{en: "to follow", hu: "követ"},
{en: "tall", hu: "magas"},
{en: "young", hu: "fiatal"},
{en: "long", hu: "hosszú"},
{en: "red hair", hu: "vörös haj"},
{en: "green", hu: "zöld"},
{en: "glasses", hu: "magas"},
{en: "high-heeled shoes", hu: "magas sarkú cipő"},
{en: "grey", hu: "szürke"},
{en: "dark grey", hu: "sötét szürke"},
{en: "a skirt", hu: "szoknya"},
{en: "a jacket", hu: "kabátka"},
{en: "a handbag", hu: "retikül"},
{en: "a shoulder", hu: "váll"},
{en: "a shoulder bag", hu: "válltáska"},
{en: "a plastic bag", hu: "nejlonzacskó"},
{en: "a carrier bag", hu: "műanyag szatyor"},
{en: "conversation", hu: "beszélgetés"},
{en: "receptionist", hu: "recepciós"},
{en: "appointment", hu: "időpont"},
{en: "foyer", hu: "hall/receoció"},
{en: "male", hu: "férfi"},
{en: "female", hu: "női"},
{en: "to apply for a job", hu: "álláshírdetésre jelentkezni"},
{en: "memory", hu: "memória"},
{en: "surname", hu: "vezetéknév"},
{en: "odd", hu: "furcsa"},
{en: "strange", hu: "furcsa"},
{en: "weird", hu: "furcsa"},
{en: "to catch up", hu: "utolér"},
{en: "relevant", hu: "lényeges"},
{en: "irrelevant", hu: "lényegtelen"},
{en: "to check", hu: "ellenőriz"},
{en: "second-hand", hu: "használt"},
{en: "connected to something", hu: "valamihez kapcsolódó"},
{en: "for example", hu: "például"},
{en: "used", hu: "használt"},
{en: "brand new", hu: "vadonatúj"},
{en: "completely", hu: "teljesen"},
{en: "to advertise", hu: "reklámoz"},
{en: "advertisment, advert, ad'", hu: "reklám"},
{en: "condition", hu: "állapot"},
{en: "state", hu: "állapot"},
{en: "mileage", hu: "megtett kilóméter"},
{en: "to service", hu: "karbantart"},
{en: "steering", hu: "jármű kormányzása"},
{en: "brakes", hu: "a fék rendszer"},
{en: "geabox", hu: "sebeségváltómű"},
{en: "to repair", hu: "javít"},
{en: "to fix", hu: "javít"},
{en: "dangerous", hu: "veszélyes"},
{en: "an accident", hu: "baleset"},
{en: "size", hu: "méret"},
{en: "an alarm system", hu: "riasztóberendezés"},
{en: "security", hu: "biztonság"},
{en: "to be in charge of something", hu: "felelős valamiért"},
{en: "martial art", hu: "harcművészet"},
{en: "up", hu: "fel"},
{en: "down", hu: "le"},
{en: "under", hu: "alatt"},
{en: "over", hu: "fölött"},
{en: "fence", hu: "kerítes"},
{en: "neighbour", hu: "szomszéd"},
{en: "to", hu: "hez/hoz"},
{en: "towards", hu: "felé"},
{en: "destination", hu: "úticél"},
{en: "along", hu: "mentén"},
{en: "across", hu: "át"},
{en: "cul-de-sac", hu: "zsákutca"},
{en: "through", hu: "keresztül"},
{en: "bullet", hu: "golyó"},
{en: "to get dressed", hu: "felöltözik"},
{en: "hole", hu: "lyuk"},
{en: "shirt sleeve", hu: "ingujj"},
{en: "coat sleeve", hu: "kabátujj"},
{en: "several", hu: "néhány"},
{en: "traffic lights", hu: "közlekedési lámpa"},
{en: "to get lost", hu: "eltéved"},
{en: "onwards", hu: "előre"},
{en: "crack an egg (cracked an egg)", hu: "tojást feltörni"},
{en: "scrambled eggs", hu: "rántotta"},
{en: "poach (poached)", hu: "buggyant"},
{en: "a poached egg", hu: "buggyant tojás"},
{en: "mix (mixed)", hu: "kever"},
{en: "pour (poured)", hu: "önt"},
{en: "wait (waited)", hu: "vár"},
{en: "firm", hu: "szilárd"},
{en: "stir (stirred)", hu: "megkever"},
{en: "a spatula", hu: "szedőlapát"},
{en: "wooden", hu: "fából való"},
{en: "plastic", hu: "műanyag"},
{en: "a frying pan", hu: "serpenyő"},
{en: "a saucepan", hu: "lábos"},
{en: "brand-new", hu: "vadonatúj"},
{en: "slowly", hu: "lassan"},
{en: "quick", hu: "gyors"},
{en: "finish", hu: "befejeződik"},
{en: "in a hurry", hu: "sietve"},
{en: "in a rush", hu: "sietve"},
{en: "hurry - hurried", hu: "siet"},
{en: "rush (rushed)", hu: "siet"},
{en: "spend time (spent time)", hu: "időt tölteni"},
{en: "make sure (made sure)", hu: "meggyőződik"},
{en: "a mistake", hu: "hiba"},
{en: "bomb disposal expert", hu: "bombaszakértő"},
{en: "fast", hu: "gyors/gyorsan"},
{en: "cutlery", hu: "evőeszköz"},
{en: "fork", hu: "villa"},
{en: "knife", hu: "kés"},
{en: "spoon", hu: "kanál"},
{en: "salt", hu: "só"},
{en: "pepper", hu: "bors"},
{en: "sugar", hu: "cukor"},
{en: "sweetener", hu: "édesítő"},
{en: "what?", hu: "mi?"},
{en: "how?", hu: "hogy?/hogyan?"},
{en: "when", hu: "amikor"},
{en: "when?", hu: "mikor?"},
{en: "why?", hu: "miért?"},
{en: "how long?", hu: "mennyi ideig?"},
{en: "who?", hu: "ki?"},
{en: "which?", hu: "melyik?"},
{en: "blue whale", hu: "kék bálna"},
{en: "traffic lights", hu: "közlekedési lámpa"},
{en: "free", hu: "szabad"},
{en: "slightly", hu: "kissé"},
{en: "formal", hu: "formális"},
{en: "more formal", hu: "formálisabb"},
{en: "fling (flung)", hu: "dob"},
{en: "toss (tossed)", hu: "hajít"},
{en: "busy", hu: "elfoglalt"},
{en: "expect (expected)", hu: "számít valamire"},
{en: "what name?", hu: "milyen név alatt?"},
{en: "sit down (sat down)", hu: "leül"},
{en: "season (seasoned)", hu: "fűszeresz/ízesít"},
{en: "pick something up (picked something up)", hu: "felvesz valamit"},
{en: "shake (shook)", hu: "megráz"},
{en: "add", hu: "hozzáad"},
{en: "grind (ground)", hu: "darál"},
{en: "too much", hu: "túl sok"},
{en: "fill (filled)", hu: "tölt"},
{en: "bet", hu: "fogod"},
{en: "sneeze (sneezed)", hu: "tüsszent"},
{en: "Finally", hu: "végül"},
{en: "tell (ld)", hu: "mond"},
{en: "open (opened)", hu: "kinyit"},
{en: "calm down (calmed down)", hu: "csillapodik"},
{en: "finish (finished)", hu: "befejeződik"},
{en: "drink (drank)", hu: "iszik"},
{en: "apple juice", hu: "almalé"},
{en: "mineral water", hu: "ásványvíz"},
{en: "carbonated", hu: "szénsavas"},
{en: "bubble", hu: "buborék"},
{en: "still mineral water", hu: "szénsavmentes ásványvíz"},
{en: "clear (cleared)", hu: "leszed"},
{en: "clear away (cleared away)", hu: "eltakarít"},
{en: "put (put)", hu: "tesz"},
{en: "dishwasher", hu: "mosogotógép"},
{en: "turn something on (turned on)", hu: "bekapcsol"},
{en: "start (started)", hu: "kezd"},
{en: "put back (put back)", hu: "visszatesz"},
{en: "fridge", hu: "hűtőszekrény"},
{en: "a cloth", hu: "törlő"},
{en: "damp", hu: "nedves"},
{en: "wipe (wiped)", hu: "töröl"},
{en: "clean (cleaned)", hu: "takarít"},
{en: "throw away (threw away)", hu: "eldob"},
{en: "crumbs", hu: "morzsa"},
{en: "outside", hu: "kint"},
{en: "a dish", hu: "tál"},
{en: "reply (replied)", hu: "válaszol"},
{en: "be in a good mood (was)", hu: "jó kedve van valakinek"},
{en: "catch up with somebody", hu: "utolér valakit"},
{en: "sort", hu: "fajta"},
{en: "type", hu: "típus"},
{en: "kitchen sink", hu: "konyhai mosogató"},
{en: "postman", hu: "postás"},
{en: "I'm sure", hu: "biztos vagyok benne"},
{en: "need", hu: "szüksége van"},
{en: "hang on!", hu: "várj!"},
{en: "hear (heard)", hu: "hall"},
{en: "deliver (delivered)", hu: "szállít/kézbesít"},
{en: "an invitation", hu: "meghívás"},
{en: "invite", hu: "meghív"},
{en: "a bill", hu: "számla"},
{en: "last chance", hu: "utolsó lehetőség"},
{en: "envelope", hu: "boríték"},
{en: "Dear Miss Swett", hu: "Kedves Swett kisasszony"},
{en: "offer (offered)", hu: "kinál"},
{en: "in my opinion", hu: "véleményem szerint"},
{en: "suitable", hu: "megfelelő"},
{en: "most suitable", hu: "a legmegfelelőbb"},
{en: "candidate", hu: "jelölt"},
{en: "security manager", hu: "biztonsági igazgató"},
{en: "experience (experienced)", hu: "tapasztal"},
{en: "experience", hu: "tapasztalat"},
{en: "teach (taught)", hu: "tanít"},
{en: "self-defence", hu: "önvédelem"},
{en: "combine (combined)", hu: "összekapcsol"},
{en: "combination", hu: "összeállítás"},
{en: "knowledge", hu: "tudás"},
{en: "expert knowledge", hu: "szaktudás"},
{en: "officially", hu: "hivatalosan"},
{en: "accept (accepted)", hu: "elfogad"},
{en: "contact (contacted)", hu: "kapcsolatba lép"},
{en: "convenient", hu: "kényelmes"},
{en: "congratulate (congratulated)", hu: "gratulál"},
{en: "congratulations", hu: "gratulálok"},
{en: "well done!", hu: "bravó!"},
{en: "interested in", hu: "érdekli valami"},
{en: "manager", hu: "igazgató"},
{en: "chart", hu: "táblázat"},
{en: "save time", hu: "időt spórol"},
{en: "save money", hu: "pénzt spórol"},
{en: "native speaker", hu: "anyanyelvű"},
{en: "square", hu: "tér"},
{en: "reserve - reserved", hu: "lefoglal"},
{en: "check - checked", hu: "ellenőriz"},
{en: "free", hu: "szabad"},
{en: "a conversation", hu: "beszélgetés"},
{en: "book", hu: "lefoglal"},
{en: "look at", hu: "megnéz"},
{en: "order", hu: "rendel"},
{en: "bring - brought", hu: "hoz"},
{en: "a pint", hu: "0.568 liter"},
{en: "draught beer", hu: "csapolt sör"},
{en: "chips", hu: "hasábburgonya"},
{en: "rare", hu: "angolos/véres"},
{en: "medium rare", hu: "félig nyers"},
{en: "medium", hu: "közepesen átsült"},
{en: "well-done", hu: "teljesen átsült"},
{en: "write something down - wrote down", hu: "leír"},
{en: "a toast", hu: "pohárköszöntő"},
{en: "ast someone's health", hu: "iszik valaki egészégére"},
{en: "clink glasses", hu: "koccint"},
{en: "topic", hu: "téma"},
{en: "topical", hu: "aktuális"},
{en: "this isn't what I ordered", hu: "Nem ezt rendeltem"},
{en: "this food is cold", hu: "ez az étel hideg"},
{en: "will my food be long?", hu: "sokat kell még várni a ételemre?"},
{en: "this food doesn't taste fresh", hu: "Ez az étel nem tűnik frissnek"},
{en: "this food is off", hu: "Ez az étel romlott"},
{en: "compensate - compensated", hu: "kárpótol"},
{en: "to come", hu: "jön"},
{en: "to go", hu: "megy"},
{en: "to live", hu: "él"},
{en: "to work", hu: "dolgozik"},
{en: "to read", hu: "olvas"},
{en: "to write", hu: "ír"},
{en: "to drive", hu: "vezet"},
{en: "to walk", hu: "sétál"},
{en: "to run", hu: "fut"},
{en: "to swim", hu: "uszik"},
{en: "to like", hu: "kedvel/tetszik"},
{en: "to love", hu: "szeret"},
{en: "to wash", hu: "mos"},
{en: "to wake up", hu: "felébred"},
{en: "to get up", hu: "felkel"},
{en: "to fly", hu: "repül"},
{en: "to play", hu: "játszik"},
{en: "to carry", hu: "visz"},
{en: "always", hu: "mindig"},
{en: "never", hu: "soha"},
{en: "every day", hu: "mindennap"},
{en: "every saturday", hu: "minden szombaton"},
{en: "sometimes", hu: "néha"},
{en: "three times a week", hu: "hetente háromszor"},
{en: "every weekend", hu: "minden hétvégen"},
{en: "twice a year", hu: "évente kétszer"},
{en: "usually", hu: "általában"},
{en: "normally", hu: "általában"},
{en: "always", hu: "mindig"},
{en: "nearly always", hu: "majd nem mindig"},
{en: "true", hu: "igaz"},
{en: "false", hu: "nem igaz"},
{en: "butcher", hu: "hentes"},
{en: "nurse", hu: "nővér"},
{en: "soldier", hu: "katona"},
{en: "dentist", hu: "fogorvos"},
{en: "cleaner", hu: "takaritó"},
{en: "bus driver", hu: "autóbuszvezető"},
{en: "shop assistant", hu: "eladó"},
{en: "waiter", hu: "pincer"},
{en: "to cut", hu: "vág"},
{en: "meat", hu: "hús"},
{en: "to help", hu: "segít"},
{en: "to defend", hu: "véd"},
{en: "to look after", hu: "gondoskodik"},
{en: "to clean", hu: "takarít"},
{en: "a building", hu: "épület"},
{en: "to drive", hu: "vezet"},
{en: "to sell", hu: "elad"},
{en: "thing", hu: "dolog"},
{en: "to bring", hu: "hoz"},
{en: "a drink", hu: "egy ital"},
{en: "food", hu: "étel"},
{en: "to pronounce", hu: "kiejt"},
{en: "pronunciation", hu: "kiejtés"},
{en: "ability", hu: "képeség"},
{en: "possible", hu: "lehetséges"},
{en: "not possible", hu: "nem lehetséges"},
{en: "impossible", hu: "lehetetlen"},
{en: "polite", hu: "udvarias"},
{en: "impolite", hu: "udvariatlan"},
{en: "rude (very impolite)", hu: "goromba"},
{en: "of course", hu: "természetesen"},
{en: "to receive", hu: "kap"},
{en: "to get", hu: "kap"},
{en: "a question", hu: "kérdés"},
{en: "an answer", hu: "válasz"},
{en: "to ask a question", hu: "kérdez"},
{en: "to reply", hu: "válaszol"},
{en: "just a moment", hu: "egy pillanat"},
{en: "to compare", hu: "összehasonlít"},
{en: "a comparison", hu: "összehasonlítás"},
{en: "same", hu: "ugyanaz"},
{en: "similar", hu: "hasanló"},
{en: "different", hu: "különböző"},
{en: "to spot", hu: "észrevész"},
{en: "like", hu: "tetszik"},
{en: "love", hu: "szeret"},
{en: "want", hu: "akar"},
{en: "need", hu: "szüksége van"},
{en: "know", hu: "tud"},
{en: "understand", hu: "ért"},
{en: "remember", hu: "emlékszik"},
{en: "forget", hu: "elfelejt"},
{en: "prefer", hu: "jobban tetszik"},
{en: "hate", hu: "gyűlöl"},
{en: "mean", hu: "gondol"},
{en: "believe", hu: "hisz"},
{en: "hammer", hu: "kalapács"},
{en: "sideburns", hu: "pajesz"},
{en: "to fight", hu: "harcol"},
{en: "crime fighter", hu: "bűnezésellen harcos"},
{en: "superhero", hu: "szuperhős"},
{en: "to exercise", hu: "edz"},
{en: "to work out (synonym for exercise)", hu: "edz"},
{en: "permanent", hu: "állandó"},
{en: "temporary", hu: "átmeneti"},
{en: "always", hu: "mindig"},
{en: "never", hu: "soha"},
{en: "sometimes", hu: "néha"},
{en: "usually", hu: "általában"},
{en: "often", hu: "gyakran"},
{en: "occupation", hu: "foglalkozás"},
{en: "job", hu: "állás"},
{en: "cocktail", hu: "koktél"},
{en: "unicorn", hu: "egyszarvú"},
{en: "parrot", hu: "papagai"},
{en: "horse", hu: "ló"},
{en: "cheetah", hu: "gepárd"},
{en: "kangaroo", hu: "kengurú"},
{en: "elephant", hu: "elefánt"},
{en: "frog", hu: "béka"},
{en: "fly", hu: "légy"},
{en: "wing", hu: "szárny"},
{en: "to kill", hu: "öl"},
{en: "to destroy", hu: "elpusztít"},
{en: "a planet", hu: "bolygó"},
{en: "a magazine", hu: "magazin"},
{en: "a magazine cover", hu: "címlap"},
{en: "it's raining", hu: "esik az eső"},
{en: "street", hu: "utca"},
{en: "wet", hu: "vizes"},
{en: "to fall", hu: "esni"},
{en: "sky", hu: "ég"},
{en: "puddle", hu: "tócsa"},
{en: "umbrella", hu: "esernyő"},
{en: "windscreen wipers", hu: "ablaktörlő"},
{en: "mask", hu: "álarc"},
{en: "shoulder pad", hu: "válltömés"},
{en: "top", hu: "felső"},
{en: "strong", hu: "erős"},
{en: "biceps", hu: "bicepsz"},
{en: "haircut", hu: "frizura"},
{en: "like", hu: "tetszik"},
{en: "love", hu: "szeret"},
{en: "want", hu: "akar"},
{en: "need", hu: "szüksége van"},
{en: "know", hu: "tud"},
{en: "understand", hu: "ért"},
{en: "remember", hu: "emlékszik"},
{en: "forget", hu: "elfelejt"},
{en: "prefer", hu: "jobban tetszik"},
{en: "hate", hu: "gyűlöl"},
{en: "mean", hu: "gondol"},
{en: "believe", hu: "hisz"},
{en: "sibling", hu: "testvér"},
{en: "boot", hu: "csizma/bakancs"},
{en: "ankle", hu: "boka"},
{en: "uncle", hu: "nagybátya"},
{en: "aunt", hu: "nagynéni"},
{en: "nephew", hu: "unokaöcs"},
{en: "niece", hu: "unokahúg"},
{en: "to compare", hu: "ősszehasonlít"},
{en: "similarity", hu: "hasonlóság"},
{en: "difference", hu: "különbség"},
{en: "petrol", hu: "benzin"},
{en: "cheap", hu: "olcsó"},
{en: "petrol station", hu: "benzinkút"},
{en: "remote control", hu: "távirányitó"},
{en: "to make a decision", hu: "dönteni"},
{en: "old", hu: "öreg / idős"},
{en: "older", hu: "öregebb / idősebb"},
{en: "young", hu: "fiatal"},
{en: "younger", hu: "fiatalabb"},
{en: "short", hu: "alacsony (személy) / rövid"},
{en: "shorter", hu: "alacsonyabb (személy) / rövidebb"},
{en: "happy", hu: "boldog"},
{en: "happier", hu: "boldogabb"},
{en: "easy", hu: "könnyű"},
{en: "easier", hu: "könnyebb"},
{en: "early", hu: "korán/korai"},
{en: "earlier", hu: "korábban/korábbi"},
{en: "careful", hu: "óvatos"},
{en: "more careful", hu: "óvatasabb"},
{en: "expensive", hu: "drága"},
{en: "more expensive", hu: "drágább"},
{en: "interesting", hu: "érdekes"},
{en: "more interesting", hu: "érdekesseb"},
{en: "good", hu: "jó"},
{en: "well", hu: "jól"},
{en: "better", hu: "jobb"},
{en: "bad", hu: "rossz"},
{en: "worse", hu: "rosszabb"},
{en: "old", hu: "régi / öreg"},
{en: "older", hu: "régibb / öregebb"},
{en: "large", hu: "nagy"},
{en: "larger", hu: "nagyobb"},
{en: "strong", hu: "erős"},
{en: "stronger", hu: "erősebb"},
{en: "modern", hu: "korszerű"},
{en: "more modern", hu: "korszerűbb"},
{en: "intelligent", hu: "intelligens"},
{en: "more intelligent", hu: "intelligensebb"},
{en: "easy", hu: "könnyű"},
{en: "hard/difficult", hu: "nehéz"},
{en: "easier", hu: "könnyebb"},
{en: "harder / more difficult", hu: "nehezebb"},
{en: "cold", hu: "hideg"},
{en: "hot", hu: "forró"},
{en: "colder", hu: "hidegebb"},
{en: "hotter", hu: "forró"},
{en: "good", hu: "jó"},
{en: "bad", hu: "rossz"},
{en: "better", hu: "jobb"},
{en: "worse", hu: "rosszabb"},
{en: "grandparent", hu: "nagyszülő"},
{en: "grandparents", hu: "nagyszülők"},
{en: "grandchild", hu: "unoka"},
{en: "grandson", hu: "fiúunoka"},
{en: "granddaughter", hu: "lányunoka"},
{en: "father-in-law", hu: "após"},
{en: "mother-in-law", hu: "anyós"},
{en: "son-in-law", hu: "vej"},
{en: "daughter-in-law", hu: "meny"},
{en: "piffle", hu: "szamárság"},
{en: "luck", hu: "szerencse"},
{en: "lucky", hu: "szerencsés"},
{en: "unlucky", hu: "szerencsétlen"},
{en: "certain", hu: "biztos"},
{en: "to introduce", hu: "bemutat"},
{en: "question mark", hu: "kérdőjel"},
{en: "question", hu: "kérdés"},
{en: "a uniform", hu: "egyenruha"},
{en: "he's asleep", hu: "alszik"},
{en: "accident", hu: "baleset"},
{en: "motorway", hu: "autópálya"},
{en: "today", hu: "ma"},
{en: "yesterday", hu: "tegnap"},
{en: "the day before yesterday", hu: "tegnapelőtt"},
{en: "tomorrow", hu: "holnap"},
{en: "the day after tomorrow", hu: "holnapután"},
{en: "swift", hu: "gyors"},
{en: "swiftly", hu: "gyorsan"},
{en: "confident", hu: "magabiztos"},
{en: "to jump", hu: "ugrik"},
{en: "place", hu: "hely"},
{en: "movement", hu: "mozgás"},
{en: "ATM", hu: "bankautomata"},
{en: "lock", hu: "zár"},
{en: "to open", hu: "kinyit"},
{en: "to put into gear", hu: "sebességbe kapcsol"},
{en: "would you like?", hu: "szeretne?"},
{en: "want", hu: "akar"},
{en: "what would you like?", hu: "Mit szeretne?"},
{en: "What do you want?", hu: "Mit akarsz?"},
{en: "polite", hu: "udvarias"},
{en: "impolite", hu: "udvariatlan"},
{en: "rude", hu: "goromba"},
{en: "awful", hu: "szörnyű"},
{en: "terrible", hu: "borzasztó"},
{en: "horrible", hu: "rémes"},
{en: "deaf", hu: "süket"},
{en: "staff", hu: "személyzet"},
{en: "to offer", hu: "kinál/ajánl"},
{en: "nice", hu: "kedves"},
{en: "popular", hu: "népszerű"},
{en: "unpopular", hu: "népszerűtlen"},
{en: "general", hu: "általános"},
{en: "specific", hu: "konkrét"},
{en: "to work", hu: "dolgozik"},
{en: "to record", hu: "felvesz"},
{en: "to watch", hu: "figyel"},
{en: "to bake", hu: "süt"},
{en: "to copy", hu: "másol"},
{en: "to carry", hu: "visz"},
{en: "to marry", hu: "házasodik"},
{en: "to study", hu: "tanul"},
{en: "a winery", hu: "borászat"},
{en: "a cellar", hu: "pince"},
{en: "dinner", hu: "vacsora"},
{en: "A restaurant", hu: "étterem"},
{en: "pork", hu: "disznóhús"},
{en: "chicken", hu: "csirke"},
{en: "spinach", hu: "spenót"},
{en: "pumpkin", hu: "tök"},
{en: "mashed potato", hu: "krumplipüré"},
{en: "to begin", hu: "kezd"},
{en: "to buy", hu: "vesz"},
{en: "to drink", hu: "iszik"},
{en: "to eat", hu: "eszik"},
{en: "to forget", hu: "elfelejt vmit"},
{en: "to find", hu: "talál"},
{en: "to give", hu: "ad"},
{en: "to go", hu: "megy"},
{en: "to pay", hu: "fizet"},
{en: "to put", hu: "rak"},
{en: "to read", hu: "olvas"},
{en: "to say", hu: "mond"},
{en: "to speak", hu: "beszél"},
{en: "to stand", hu: "áll"},
{en: "to think", hu: "gondol"},
{en: "potato", hu: "burgonya"},
{en: "onion", hu: "hagyma"},
{en: "goose", hu: "liba"},
{en: "turkey", hu: "pulyka"},
{en: "Christmas present", hu: "karácsonyi ajándék"},
{en: "Christmas carol", hu: "ének"},
{en: "a tie", hu: "nyakkendő"},
{en: "skull", hu: "koponya"},
{en: "gloves", hu: "kesztyű"},
{en: "wooly hat", hu: "kötött sapka"},
{en: "to wrap", hu: "csomagol"},
{en: "to decorate", hu: "díszit"},
{en: "vegetables", hu: "zöldség"},
{en: "carrot", hu: "sárgarépa"},
{en: "Brussels sprout", hu: "kellbimbó"},
{en: "cabbage", hu: "káposzta"},
{en: "meat", hu: "hús"},
{en: "goose leg", hu: "libacomb"},
{en: "garlic", hu: "fokhagyma"},
{en: "to buy - bought", hu: "vesz"},
{en: "to bring - brought", hu: "hoz"},
{en: "recipe", hu: "recept"},
{en: "ingredients", hu: "összetevők/hozzávalók"},
{en: "flour", hu: "liszt"},
{en: "bicarbonate of soda", hu: "szódabikárbóna"},
{en: "teaspoon", hu: "teáskanál"},
{en: "table spoon", hu: "evőkanál"},
{en: "ginger", hu: "gyömbér"},
{en: "to grind - gound", hu: "őröl"},
{en: "ground", hu: "őrölt"},
{en: "cinnamon", hu: "fahéj"},
{en: "I don't know", hu: "Nem tudom"},
{en: "I don't care", hu: "Nem érdekel"},
{en: "to forget - forgot", hu: "elfeléjt"},
{en: "not important", hu: "nem fontos"},
{en: "egg", hu: "tojás"},
{en: "to lay an egg", hu: "tojást tojni"},
{en: "fried egg", hu: "tükörtojás"},
{en: "molasses", hu: "mélasz"},
{en: "viscous", hu: "nyúlos"},
{en: "sieve", hu: "szita"},
{en: "to sift - sifted", hu: "szitál"},
{en: "food mixer", hu: "konyhai robotgép"},
{en: "to mix", hu: "kever"},
{en: "to rub", hu: "dörsöl"},
{en: "to collect", hu: "összegyűlik"},
{en: "to throw", hu: "dob"},
{en: "breadcrumbs", hu: "morzsa"},
{en: "fork", hu: "villa"},
{en: "whisk", hu: "habverő"},
{en: "rolling pin", hu: "sodrófa"},
{en: "to confuse - confused", hu: "összezavar"},
{en: "confused", hu: "zavart"},
{en: "to celebrate", hu: "ünnepel"},
{en: "a source", hu: "forrás"},
{en: "Religious festival", hu: "vallási ünnep"},
{en: "the day before", hu: "előző nap"},
{en: "to play", hu: "játszik"},
{en: "to prepare", hu: "készít"},
{en: "to organise", hu: "szervez"},
{en: "to turn on", hu: "bekapcsol"},
{en: "to turn off", hu: "kikapcsol"},
{en: "a hob", hu: "főzőlap"},
{en: "an oven", hu: "sütő"},
{en: "important", hu: "fontos"},
{en: "stress", hu: "stressz"},
{en: "naturally", hu: "természetesen"},
{en: "tradition", hu: "hagyomány"},
{en: "traditionally", hu: "hagyonmányosan"},
{en: "it depends", hu: "attól függ"},
{en: "tree trunnk", hu: "fatörzs"},
{en: "fairy lights", hu: "karácsonyi égők"},
{en: "Christmas songs", hu: "karácsonyi dalok"},
{en: "nasty", hu: "komisz"},
{en: "a miser", hu: "fösvény"},
{en: "to spend", hu: "költ"},
{en: "to hate", hu: "gyűlöl"},
{en: "to collect", hu: "gyűjt"},
{en: "pots of money", hu: "nagyon sok pénz"},
{en: "huge amounts of cash", hu: "készpénz rengetek mennyiségben"},
{en: "old", hu: "öreg"},
{en: "candle", hu: "gyertya"},
{en: "a money-lender", hu: "hitelező"},
{en: "a usurer", hu: "uzsora"},
{en: "to charge interest", hu: "kamatot felszámít"},
{en: "fair", hu: "tiszteséges"},
{en: "to exploit", hu: "kihasznál"},
{en: "nice", hu: "kedves"},
{en: "to check", hu: "elenőriz"},
{en: "on time", hu: "időben"},
{en: "to be late", hu: "késik"},
{en: "to deduct", hu: "levon"},
{en: "salt", hu: "só"},
{en: "lunchtime", hu: "ebédidő"},
{en: "toilet paper", hu: "WC papír"},
{en: "day off", hu: "szabadnap"},
{en: "to count", hu: "számol"},
{en: "a ghost", hu: "szellem"},
{en: "almost", hu: "majdnem"},
{en: "to wet the bed", hu: "az ágyba vízelni"},
{en: "business", hu: "cég"},
{en: "to be nice", hu: "kedves lenni"},
{en: "to spend", hu: "költ"},
{en: "for ever and ever", hu: "örökké"},
{en: "to show", hu: "mutat"},
{en: "portable", hu: "hordazható"},
{en: "to remind", hu: "emlékeztet"},
{en: "a girlfriend", hu: "barátnő"},
{en: "a boss", hu: "főnök"},
{en: "to leave", hu: "elmegy"},
{en: "to arrive", hu: "érkezik"},
{en: "dead", hu: "halott"},
{en: "to die", hu: "meghal"},
{en: "nobody", hu: "senki"},
{en: "to visit", hu: "látogat"},
{en: "a grave", hu: "sír"},
{en: "upset", hu: "felizgatatt"},
{en: "to feel", hu: "érez"},
{en: "a couple", hu: "pár"},
{en: "happy", hu: "boldog"},
{en: "to go to sleep - went to sleep", hu: "elalszik"},
{en: "to wake up - woke up", hu: "felébred"},
{en: "mean", hu: "fukar"},
{en: "stingy", hu: "fukar"},
{en: "horrible", hu: "szörnyű"},
{en: "expensive", hu: "drága"},
{en: "to rush - rushed", hu: "rohan"},
{en: "surprised", hu: "meglepődött"},
{en: "a present", hu: "ajándék"},
{en: "lyrics", hu: "dalszöveg"},
{en: "title", hu: "cím"},
{en: "weird", hu: "furcsa"},
{en: "partridge", hu: "fogoly"},
{en: "pear tree", hu: "körtefa"},
{en: "turtle-dove", hu: "gerle"},
{en: "blackbird", hu: "rigó"},
{en: "ring", hu: "gyűrű"},
{en: "gold", hu: "arany"},
{en: "who cares?", hu: "kit érdekel?"},
{en: "to lay an egg", hu: "tojást tojik"},
{en: "rhythm", hu: "ritmus"},
{en: "swan", hu: "hattyú"},
{en: "maid", hu: "leány"},
{en: "to leap", hu: "ugrik"},
{en: "kangaroo", hu: "kenguru"},
{en: "rabbit", hu: "nyúl"},
{en: "grasshopper", hu: "szöcske"},
{en: "piper", hu: "dudás"},
{en: "bagpipes", hu: "duda"},
{en: "a drummer", hu: "dobos"},
{en: "to drum", hu: "dobol"},
{en: "chat", hu: "cseveg;s"},
{en: "reason", hu: "ok"},
{en: "to fill", hu: "tölt"},
{en: "air", hu: "levegő"},
{en: "crescendo", hu: "fokozatos erősödés"},
{en: "to imagine - imagined", hu: "elképzel"},
{en: "stage", hu: "színpad"},
{en: "microphone", hu: "mikrofon"},
{en: "loudspeaker", hu: "hangszóró"},
{en: "lung(s)", hu: "tödő(k)"},
{en: "audience", hu: "közönség"},
{en: "ceiling", hu: "plafon"},
{en: "curly", hu: "göndör"},
{en: "straight", hu: "egyenes"},
{en: "quiet", hu: "csendes"},
{en: "loud", hu: "hangos"},
{en: "louder", hu: "hangosabb"},
{en: "to sing", hu: "énekel"},
{en: "to release", hu: "kienged"},
{en: "to damage", hu: "megkárosít"},
{en: "too much", hu: "túl sokat"},
{en: "to put on weight", hu: "hízik"},
{en: "success", hu: "siker"},
{en: "stomach", hu: "gyomor"},
{en: "permission", hu: "engedély"},
{en: "to compare", hu: "összehasonlít"},
{en: "a comparison", hu: "összehasonlítás"},
{en: "hopefully", hu: "remélhetőleg"},
{en: "to recover", hu: "felépül"},
{en: "relaxed", hu: "kipihent"},
{en: "refreshed", hu: "felfrissült"},
{en: "uncle", hu: "nagybátya"},
{en: "aunt", hu: "nagynéni"},
{en: "nephew", hu: "unokaöcs"},
{en: "niece", hu: "unokahúg"},
{en: "happy", hu: "boldog"},
{en: "happier", hu: "boldogabb"},
{en: "easy", hu: "könnyű"},
{en: "easier", hu: "könnyebb"},
{en: "early", hu: "korán/korai"},
{en: "earlier", hu: "korábban/korábbi"},
{en: "careful", hu: "óvatos"},
{en: "more careful", hu: "óvatosabb"},
{en: "expensive", hu: "drága"},
{en: "more expensive", hu: "drágább"},
{en: "interesting", hu: "érdekes"},
{en: "more interesting", hu: "érdekesebb"},
{en: "good", hu: "jó"},
{en: "well", hu: "jól"},
{en: "better", hu: "jobb"},
{en: "bad", hu: "rossz"},
{en: "worse", hu: "rosszabb"},
{en: "awful", hu: "szörnyű"},
{en: "to continue", hu: "folytatódik"},
{en: "-ish", hu: "körülbelül"},
{en: "how far from…?", hu: "milyen messze …tól/től?"},
{en: "a headache", hu: "fejfájás"},
{en: "A stomach ache", hu: "gyomorfájás"},
{en: "to hurt", hu: "fáj"},
{en: "to ache", hu: "fáj"},
{en: "painful", hu: "fájdalmos"},
{en: "a hangover", hu: "másnaposság"},
{en: "to be hung-over", hu: "másnapos"},
{en: "to have a cold", hu: "meg van fázva"},
{en: "an infection", hu: "fertőzés"},
{en: "blocked", hu: "eldugult"},
{en: "to sneeze", hu: "tüsszent"},
{en: "damp", hu: "nedves"},
{en: "wet", hu: "vizes"},
{en: "soaking wet", hu: "bőrig ázott"},
{en: "to be in the doghouse", hu: "büntetésben van"},
{en: "eccentric", hu: "különc"},
{en: "elegant", hu: "elegáns"},
{en: "ecelctic", hu: "eklektikus"},
{en: "electric eel", hu: "elektromos angolna"},
{en: "to pay attention", hu: "figyelni"},
{en: "type", hu: "típus"},
{en: "yellow-ish", hu: "sárgás"},
{en: "carbonated", hu: "szénsavas"},
{en: "bubbles", hu: "buborék"},
{en: "phrase", hu: "kifejezés"},
{en: "useful", hu: "hasznos"},
{en: "polite", hu: "udvarias"},
{en: "to order", hu: "rendel"},
{en: "a pint of beer", hu: "1 korsó sör"},
{en: "a 1/2 pint of beer", hu: "1 pohár sör"},
{en: "shandy", hu: "radler"},
{en: "lemonade", hu: "szénsavas limonádé"},
{en: "table service", hu: "kiszolgálás az asztálnál"},
{en: "counter service", hu: "kiszolgálás a pultnál"},
{en: "to tip", hu: "borravalót adni"},
{en: "a tip", hu: "borravaló"},
{en: "to finish", hu: "befejez"},
{en: "a bench", hu: "pad"},
{en: "to fall asleep", hu: "elalszik"},
{en: "wetter than", hu: "vizessebb mint…"},
{en: "to cough", hu: "köhög"},
{en: "to sneeze", hu: "tüsszent"},
{en: "to have a sore throat", hu: "faj a torka"},
{en: "to have a blocked nose", hu: "eldugult az orra"},
{en: "rabies", hu: "veszettség"},
{en: "originally", hu: "eredetileg"},
{en: "disease", hu: "betegség"},
{en: "often", hu: "gyakran"},
{en: "better", hu: "jobb"},
{en: "to convince", hu: "meggyőz"},
{en: "to realize", hu: "észrevesz"},
{en: "to decide", hu: "dönt"},
{en: "to offer", hu: "kínál/felajánl"},
{en: "to catch a cold", hu: "megfázik"},
{en: "situation", hu: "helyzet"},
{en: "realise", hu: "észrevesz"},
{en: "I'm sorry", hu: "sajnálom"},
{en: "to behave", hu: "viselkedik"},
{en: "badly", hu: "rosszul"},
{en: "to forgive", hu: "megbocsát"},
{en: "to accept", hu: "elfogad"},
{en: "the matter is closed", hu: "az ügy le van zárva"},
{en: "excuse me!", hu: "elnézést kérek!"},
{en: "Sorry!", hu: "Bocsánot!"},
{en: "to move", hu: "mozog"},
{en: "to get someone's attention", hu: "valakinek a figyelmet felhívni"},
{en: "to wave", hu: "int"},
{en: "a crowd", hu: "tömeg"},
{en: "to force", hu: "erőszakol"},
{en: "to pass", hu: "elhalad"},
{en: "to interrupt", hu: "félbeszakit"},
{en: "to miss", hu: "lemarad"},
{en: "to celebrate", hu: "ünnepel"},
{en: "celebration", hu: "ünneplés"},
{en: "noun", hu: "főnév"},
{en: "adjective", hu: "melléknév"},
{en: "adverb", hu: "határozószó"},
{en: "how", hu: "hogy/hogyan"},
{en: "quickly", hu: "gyorsan"},
{en: "slowly", hu: "lassan"},
{en: "opposite", hu: "ellentéte"},
{en: "to add", hu: "hozzáad"},
{en: "to provide", hu: "nyújt"},
{en: "thief", hu: "tolvaj"},
{en: "similar", hu: "hasonló"},
{en: "together", hu: "együtt"},
{en: "a couple", hu: "pár"},
{en: "automatically", hu: "automatikusan"},
{en: "extra", hu: "plussz"},
{en: "nice", hu: "szép"},
{en: "neat", hu: "rendezett"},
{en: "a mistake", hu: "egy hiba"},
{en: "to spell", hu: "betűz"},
{en: "quick", hu: "gyors"},
{en: "quickly", hu: "gyorsan"},
{en: "bad", hu: "rossz"},
{en: "badly", hu: "rosszul"},
{en: "easy", hu: "könnyű"},
{en: "easily", hu: "könnyen"},
{en: "heavy", hu: "nehéz"},
{en: "heavily", hu: "nehézen"},
{en: "awkward", hu: "kellemetlen"},
{en: "to accelerate", hu: "gyorsul"},
{en: "to bark", hu: "ugat"},
{en: "quiet", hu: "csendes"},
{en: "quietly", hu: "csendesen"},
{en: "loud", hu: "hangos"},
{en: "loudly", hu: "hangosan"},
{en: "a blocked nose", hu: "eldugult orr"},
{en: "a runny nose", hu: "folyik az orr"},
{en: "liquid", hu: "folyadék"},
{en: "a tissue", hu: "papír zsebkendő"},
{en: "to cough", hu: "köhög"},
{en: "to sneeze", hu: "tüsszent"},
{en: "lucky", hu: "szerencsés"},
{en: "unlucky", hu: "szerencsétlen"},
{en: "to have a temperature", hu: "valakinek láza van"},
{en: "fever", hu: "láz"},
{en: "to bump into", hu: "összefut valakivel"},
{en: "earache", hu: "fülfájás"},
{en: "toothache", hu: "fogfájás"},
{en: "backache", hu: "hátfájás"},
{en: "lumbago", hu: "lumbágó"},
{en: "to break", hu: "tör"},
{en: "broken", hu: "törött"},
{en: "leg", hu: "láb"},
{en: "arm", hu: "kar"},
{en: "finger", hu: "ujj"},
{en: "back", hu: "hát/derék"},
{en: "ankle", hu: "boka"},
{en: "I feel sick", hu: "rosszul vagyok/hányingerem van"},
{en: "to vomit", hu: "hány"},
{en: "to bump into", hu: "összefut valakivel"},
{en: "a job interview", hu: "állás interjú"},
{en: "to follow", hu: "követ"},
{en: "tall", hu: "magas"},
{en: "young", hu: "fiatal"},
{en: "long", hu: "hosszú"},
{en: "red hair", hu: "vörös haj"},
{en: "green", hu: "zöld"},
{en: "glasses", hu: "magas"},
{en: "high-heeled shoes", hu: "magas sarkú cipő"},
{en: "grey", hu: "szürke"},
{en: "dark grey", hu: "sötét szürke"},
{en: "a skirt", hu: "szoknya"},
{en: "a jacket", hu: "kabátka"},
{en: "a handbag", hu: "retikül"},
{en: "a shoulder", hu: "váll"},
{en: "a shoulder bag", hu: "válltáska"},
{en: "a plastic bag", hu: "nejlonzacskó"},
{en: "a carrier bag", hu: "műanyag szatyor"},
{en: "conversation", hu: "beszélgetés"},
{en: "receptionist", hu: "recepciós"},
{en: "appointment", hu: "időpont"},
{en: "foyer", hu: "hall/recepció"},
{en: "male", hu: "férfi"},
{en: "female", hu: "női"},
{en: "to apply for a job", hu: "álláshírdetésre jelentkezni"},
{en: "memory", hu: "memória"},
{en: "surname", hu: "vezetéknév"},
{en: "odd", hu: "furcsa"},
{en: "strange", hu: "furcsa"},
{en: "weird", hu: "furcsa"},
{en: "to catch up", hu: "utolér"},
{en: "relevant", hu: "lényeges"},
{en: "irrelevant", hu: "lényegtelen"},
{en: "to check", hu: "ellenőriz"},
{en: "second-hand", hu: "használt"},
{en: "connected to something", hu: "valamihez kapcsolódó"},
{en: "for example", hu: "például"},
{en: "used", hu: "használt"},
{en: "brand new", hu: "vadonatúj"},
{en: "completely", hu: "teljesen"},
{en: "to advertise", hu: "reklámoz"},
{en: "advertisment, advert, ad'", hu: "reklám"},
{en: "condition", hu: "állapot"},
{en: "state", hu: "állapot"},
{en: "mileage", hu: "megtett kilóméter"},
{en: "to service", hu: "karbantart"},
{en: "steering", hu: "jármű kormányzása"},
{en: "brakes", hu: "a fék rendszer"},
{en: "geabox", hu: "sebeségváltómű"},
{en: "to repair", hu: "javít"},
{en: "to fix", hu: "javít"},
{en: "dangerous", hu: "veszélyes"},
{en: "an accident", hu: "baleset"},
{en: "size", hu: "méret"},
{en: "an alarm system", hu: "riasztóberendezés"},
{en: "security", hu: "biztonság"},
{en: "to be in charge of something", hu: "felelős valamiért"},
{en: "martial art", hu: "harcművészet"},
{en: "up", hu: "fel"},
{en: "down", hu: "le"},
{en: "under", hu: "alatt"},
{en: "over", hu: "fölött"},
{en: "fence", hu: "kerítes"},
{en: "neighbour", hu: "szomszéd"},
{en: "to", hu: "hez/hoz"},
{en: "towards", hu: "felé"},
{en: "destination", hu: "úticél"},
{en: "along", hu: "mentén"},
{en: "across", hu: "át"},
{en: "cul-de-sac", hu: "zsákutca"},
{en: "through", hu: "keresztül"},
{en: "bullet", hu: "golyó"},
{en: "to get dressed", hu: "felöltözik"},
{en: "hole", hu: "lyuk"},
{en: "shirt sleeve", hu: "ingujj"},
{en: "coat sleeve", hu: "kabátujj"},
{en: "several", hu: "néhány"},
{en: "traffic lights", hu: "közlekedési lámpa"},
{en: "to get lost", hu: "eltéved"},
{en: "onwards", hu: "előre"},
{en: "crack an egg (cracked an egg)", hu: "tojást feltörni"},
{en: "scrambled eggs", hu: "rántotta"},
{en: "poach (poached)", hu: "buggyant"},
{en: "a poached egg", hu: "buggyant tojás"},
{en: "mix (mixed)", hu: "kever"},
{en: "pour (poured)", hu: "önt"},
{en: "wait (waited)", hu: "vár"},
{en: "firm", hu: "szilárd"},
{en: "stir (stirred)", hu: "megkever"},
{en: "a spatula", hu: "szedőlapát"},
{en: "wooden", hu: "fából való"},
{en: "plastic", hu: "műanyag"},
{en: "a frying pan", hu: "serpenyő"},
{en: "a saucepan", hu: "lábos"},
{en: "brand-new", hu: "vadonatúj"},
{en: "slowly", hu: "lassan"},
{en: "quick", hu: "gyors"},
{en: "finish", hu: "befejeződik"},
{en: "in a hurry", hu: "sietve"},
{en: "in a rush", hu: "sietve"},
{en: "hurry - hurried", hu: "siet"},
{en: "rush (rushed)", hu: "siet"},
{en: "spend time (spent time)", hu: "időt tölteni"},
{en: "make sure (made sure)", hu: "meggyőződik"},
{en: "a mistake", hu: "hiba"},
{en: "bomb disposal expert", hu: "bombaszakértő"},
{en: "fast", hu: "gyors/gyorsan"},
{en: "cutlery", hu: "evőeszköz"},
{en: "fork", hu: "villa"},
{en: "knife", hu: "kés"},
{en: "spoon", hu: "kanál"},
{en: "salt", hu: "só"},
{en: "pepper", hu: "bors"},
{en: "sugar", hu: "cukor"},
{en: "sweetener", hu: "édesítő"},
{en: "what?", hu: "mi?"},
{en: "how?", hu: "hogy?/hogyan?"},
{en: "when", hu: "amikor"},
{en: "when?", hu: "mikor?"},
{en: "why?", hu: "miért?"},
{en: "how long?", hu: "mennyi ideig?"},
{en: "who?", hu: "ki?"},
{en: "which?", hu: "melyik?"},
{en: "blue whale", hu: "kék bálna"},
{en: "traffic lights", hu: "közlekedési lámpa"},
{en: "free", hu: "szabad"},
{en: "slightly", hu: "kissé"},
{en: "formal", hu: "formális"},
{en: "more formal", hu: "formálisabb"},
{en: "fling (flung)", hu: "dob"},
{en: "toss (tossed)", hu: "hajít"},
{en: "busy", hu: "elfoglalt"},
{en: "expect (expected)", hu: "számít valamire"},
{en: "what name?", hu: "milyen név alatt?"},
{en: "sit down (sat down)", hu: "leül"},
{en: "season (seasoned)", hu: "fűszeresz/ízesít"},
{en: "pick something up (picked something up)", hu: "felvesz valamit"},
{en: "shake (shook)", hu: "megráz"},
{en: "add", hu: "hozzáad"},
{en: "grind (ground)", hu: "darál"},
{en: "too much", hu: "túl sok"},
{en: "fill (filled)", hu: "tölt"},
{en: "bet", hu: "fogod"},
{en: "sneeze (sneezed)", hu: "tüsszent"},
{en: "Finally", hu: "végül"},
{en: "tell (ld)", hu: "mond"},
{en: "open (opened)", hu: "kinyit"},
{en: "calm down (calmed down)", hu: "csillapodik"},
{en: "finish (finished)", hu: "befejeződik"},
{en: "drink (drank)", hu: "iszik"},
{en: "apple juice", hu: "almalé"},
{en: "mineral water", hu: "ásványvíz"},
{en: "carbonated", hu: "szénsavas"},
{en: "bubble", hu: "buborék"},
{en: "still mineral water", hu: "szénsavmentes ásványvíz"},
{en: "clear (cleared)", hu: "leszed"},
{en: "clear away (cleared away)", hu: "eltakarít"},
{en: "put (put)", hu: "tesz"},
{en: "dishwasher", hu: "mosogotógép"},
{en: "turn something on (turned on)", hu: "bekapcsol"},
{en: "start (started)", hu: "kezd"},
{en: "put back (put back)", hu: "visszatesz"},
{en: "fridge", hu: "hűtőszekrény"},
{en: "a cloth", hu: "törlő"},
{en: "damp", hu: "nedves"},
{en: "wipe (wiped)", hu: "töröl"},
{en: "clean (cleaned)", hu: "takarít"},
{en: "throw away (threw away)", hu: "eldob"},
{en: "crumbs", hu: "morzsa"},
{en: "outside", hu: "kint"},
{en: "a dish", hu: "tál"},
{en: "reply (replied)", hu: "válaszol"},
{en: "be in a good mood (was)", hu: "jó kedve van valakinek"},
{en: "catch up with somebody", hu: "utolér valakit"},
{en: "sort", hu: "fajta"},
{en: "type", hu: "típus"},
{en: "kitchen sink", hu: "konyhai mosogató"},
{en: "postman", hu: "postás"},
{en: "I'm sure", hu: "biztos vagyok benne"},
{en: "need", hu: "szüksége van"},
{en: "hang on!", hu: "várj!"},
{en: "hear (heard)", hu: "hall"},
{en: "deliver (delivered)", hu: "szállít/kézbesít"},
{en: "an invitation", hu: "meghívás"},
{en: "invite", hu: "meghív"},
{en: "a bill", hu: "számla"},
{en: "last chance", hu: "utolsó lehetőség"},
{en: "envelope", hu: "boríték"},
{en: "Dear Miss Swett", hu: "Kedves Swett kisasszony"},
{en: "offer (offered)", hu: "kinál"},
{en: "in my opinion", hu: "véleményem szerint"},
{en: "suitable", hu: "megfelelő"},
{en: "most suitable", hu: "a legmegfelelőbb"},
{en: "candidate", hu: "jelölt"},
{en: "security manager", hu: "biztonsági igazgató"},
{en: "experience (experienced)", hu: "tapasztal"},
{en: "experience", hu: "tapasztalat"},
{en: "teach (taught)", hu: "tanít"},
{en: "self-defence", hu: "önvédelem"},
{en: "combine (combined)", hu: "összekapcsol"},
{en: "combination", hu: "összeállítás"},
{en: "knowledge", hu: "tudás"},
{en: "expert knowledge", hu: "szaktudás"},
{en: "officially", hu: "hivatalosan"},
{en: "accept (accepted)", hu: "elfogad"},
{en: "contact (contacted)", hu: "kapcsolatba lép"},
{en: "convenient", hu: "kényelmes"},
{en: "congratulate (congratulated)", hu: "gratulál"},
{en: "congratulations", hu: "gratulálok"},
{en: "well done!", hu: "bravó!"},
{en: "interested in", hu: "érdekli valami"},
{en: "manager", hu: "igazgató"},
{en: "chart", hu: "táblázat"},
{en: "save time", hu: "időt spórol"},
{en: "save money", hu: "pénzt spórol"},
{en: "native speaker", hu: "anyanyelvű"},
{en: "square", hu: "tér"},
{en: "reserve - reserved", hu: "lefoglal"},
{en: "check - checked", hu: "ellenőriz"},
{en: "free", hu: "szabad"},
{en: "a conversation", hu: "beszélgetés"},
{en: "book", hu: "lefoglal"},
{en: "look at", hu: "megnéz"},
{en: "order", hu: "rendel"},
{en: "bring - brought", hu: "hoz"},
{en: "a pint", hu: "0.568 liter"},
{en: "draught beer", hu: "csapolt sör"},
{en: "chips", hu: "hasábburgonya"},
{en: "rare", hu: "angolos/véres"},
{en: "medium rare", hu: "félig nyers"},
{en: "medium", hu: "közepesen átsült"},
{en: "well-done", hu: "teljesen átsült"},
{en: "write something down - wrote down", hu: "leír"},
{en: "a toast", hu: "pohárköszöntő"},
{en: "ast someone's health", hu: "iszik valaki egészégére"},
{en: "clink glasses", hu: "koccint"},
{en: "topic", hu: "téma"},
{en: "topical", hu: "aktuális"},
{en: "this isn't what I ordered", hu: "Nem ezt rendeltem"},
{en: "this food is cold", hu: "ez az étel hideg"},
{en: "will my food be long?", hu: "sokat kell még várni a ételemre?"},
{en: "this food doesn't taste fresh", hu: "Ez az étel nem tűnik frissnek"},
{en: "this food is off", hu: "Ez az étel romlott"},
	],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
	[]
]



selectAnchorSetHref('#menuBackBtn', '../index.html')
selectAnchorSetHref('#menuHomeBtn', '../index.html')

document.querySelector('#menuForwardBtn').addEventListener('click', (e) => {
	prevDef(e);
	// if(locHashNum<5){
	// 	window.location.href = '../pages/speak10.html#' + (locHashNum + 1);
	// 	location.reload();
	// 	}
	}
)

let content = selectElement(".content");

content.addEventListener('click', ()=>{
	content.classList.toggle("clicked");
})

selectElement(".clickArea").addEventListener('click', ()=>{
	changeWords();
})

content.querySelector(".cardLangTwo").addEventListener('touchmove', ()=>{
	changeWords();
})

function changeWords() {
	let randW = words[1][Math.floor(Math.random() * words[1].length)];
	selectElement("#langOne").innerText = randW.hu;
	selectElement("#langTwo").innerText = randW.en;
}

// content.querySelector(".cardLangTwo #next").addEventListener('dblclick', ()=>{
// 		content.querySelector(".cardLangTwo").style.backgroundColor = "yellow";
// 	})
	// checkScrollPosition()
// })

// function checkScrollPosition(e) {
// 	console.log(e);
// 	const touchstart = e.originalEvent.touches[0].clientY;
// 	const touchend = e.originalEvent.changedTouches[0].clientY;

// 	const button = content.querySelector(".cardLangTwo");
// 	if (touchstart > touchend) {
// 			button.style.background = "green";
// 	} else {
// 			button.style.background = "blue";
// 	}
// }